scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:9888']
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'loki'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'loki:3100' ]
  - job_name: 'tempo'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'tempo:3200' ]