project_name: baton-sdk
builds:
  - binary: baton
    env:
      - CGO_ENABLED=0
    id: linux
    main: ./cmd/baton
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - use: buildx
    dockerfile: Dockerfile.baton
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/ductone/baton:{{ .Version }}-amd64"
      - "ghcr.io/ductone/baton:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=baton"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    dockerfile: Dockerfile.baton
    goarch: arm64
    image_templates:
      - "ghcr.io/ductone/baton:{{ .Version }}-arm64"
      - "ghcr.io/ductone/baton:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=baton"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: ghcr.io/ductone/baton:{{ .Version }}
    image_templates:
      - ghcr.io/conductorone/baton:{{ .Version }}-amd64
      - ghcr.io/conductorone/baton:{{ .Version }}-arm64
  - name_template: ghcr.io/conductorone/baton:latest
    image_templates:
      - ghcr.io/conductorone/baton:latest-amd64
      - ghcr.io/conductorone/baton:latest-arm64
checksum:
  disable: true
release:
  disable: true
changelog:
  skip: true