// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: c1/connectorapi/baton/v1/servedpolicy.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ServedPolicyEnvelope with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ServedPolicyEnvelope) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServedPolicyEnvelope with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ServedPolicyEnvelopeMultiError, or nil if none found.
func (m *ServedPolicyEnvelope) ValidateAll() error {
	return m.validate(true)
}

func (m *ServedPolicyEnvelope) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EnvelopeVersion

	// no validation rules for RevisionId

	// no validation rules for RevisionRootDigest

	// no validation rules for ConfigVersion

	if all {
		switch v := interface{}(m.GetEgress()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ServedPolicyEnvelopeValidationError{
					field:  "Egress",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ServedPolicyEnvelopeValidationError{
					field:  "Egress",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEgress()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ServedPolicyEnvelopeValidationError{
				field:  "Egress",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ServedPolicyEnvelopeMultiError(errors)
	}

	return nil
}

// ServedPolicyEnvelopeMultiError is an error wrapping multiple validation
// errors returned by ServedPolicyEnvelope.ValidateAll() if the designated
// constraints aren't met.
type ServedPolicyEnvelopeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServedPolicyEnvelopeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServedPolicyEnvelopeMultiError) AllErrors() []error { return m }

// ServedPolicyEnvelopeValidationError is the validation error returned by
// ServedPolicyEnvelope.Validate if the designated constraints aren't met.
type ServedPolicyEnvelopeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServedPolicyEnvelopeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServedPolicyEnvelopeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServedPolicyEnvelopeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServedPolicyEnvelopeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServedPolicyEnvelopeValidationError) ErrorName() string {
	return "ServedPolicyEnvelopeValidationError"
}

// Error satisfies the builtin error interface
func (e ServedPolicyEnvelopeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServedPolicyEnvelope.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServedPolicyEnvelopeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServedPolicyEnvelopeValidationError{}

// Validate checks the field values on EgressSection with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EgressSection) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EgressSection with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EgressSectionMultiError, or
// nil if none found.
func (m *EgressSection) ValidateAll() error {
	return m.validate(true)
}

func (m *EgressSection) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SchemaVersion

	// no validation rules for RecordedEgressDerivationDigest

	// no validation rules for HttpsOnly

	if len(errors) > 0 {
		return EgressSectionMultiError(errors)
	}

	return nil
}

// EgressSectionMultiError is an error wrapping multiple validation errors
// returned by EgressSection.ValidateAll() if the designated constraints
// aren't met.
type EgressSectionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EgressSectionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EgressSectionMultiError) AllErrors() []error { return m }

// EgressSectionValidationError is the validation error returned by
// EgressSection.Validate if the designated constraints aren't met.
type EgressSectionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EgressSectionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EgressSectionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EgressSectionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EgressSectionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EgressSectionValidationError) ErrorName() string { return "EgressSectionValidationError" }

// Error satisfies the builtin error interface
func (e EgressSectionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEgressSection.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EgressSectionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EgressSectionValidationError{}
