// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: c1/connectorapi/baton/v1/session.proto

//go:build protoopaque

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SyncId string                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3"`
	xxx_hidden_Key    string                 `protobuf:"bytes,2,opt,name=key,proto3"`
	xxx_hidden_Prefix string                 `protobuf:"bytes,3,opt,name=prefix,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRequest) GetSyncId() string {
	if x != nil {
		return x.xxx_hidden_SyncId
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *GetRequest) GetPrefix() string {
	if x != nil {
		return x.xxx_hidden_Prefix
	}
	return ""
}

func (x *GetRequest) SetSyncId(v string) {
	x.xxx_hidden_SyncId = v
}

func (x *GetRequest) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *GetRequest) SetPrefix(v string) {
	x.xxx_hidden_Prefix = v
}

type GetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SyncId string
	Key    string
	Prefix string
}

func (b0 GetRequest_builder) Build() *GetRequest {
	m0 := &GetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SyncId = b.SyncId
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Prefix = b.Prefix
	return m0
}

type GetResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value []byte                 `protobuf:"bytes,1,opt,name=value,proto3"`
	xxx_hidden_Found bool                   `protobuf:"varint,2,opt,name=found,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.xxx_hidden_Found
	}
	return false
}

func (x *GetResponse) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
}

func (x *GetResponse) SetFound(v bool) {
	x.xxx_hidden_Found = v
}

type GetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value []byte
	Found bool
}

func (b0 GetResponse_builder) Build() *GetResponse {
	m0 := &GetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Found = b.Found
	return m0
}

type GetManyRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SyncId string                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3"`
	xxx_hidden_Keys   []string               `protobuf:"bytes,2,rep,name=keys,proto3"`
	xxx_hidden_Prefix string                 `protobuf:"bytes,3,opt,name=prefix,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetManyRequest) Reset() {
	*x = GetManyRequest{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManyRequest) ProtoMessage() {}

func (x *GetManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetManyRequest) GetSyncId() string {
	if x != nil {
		return x.xxx_hidden_SyncId
	}
	return ""
}

func (x *GetManyRequest) GetKeys() []string {
	if x != nil {
		return x.xxx_hidden_Keys
	}
	return nil
}

func (x *GetManyRequest) GetPrefix() string {
	if x != nil {
		return x.xxx_hidden_Prefix
	}
	return ""
}

func (x *GetManyRequest) SetSyncId(v string) {
	x.xxx_hidden_SyncId = v
}

func (x *GetManyRequest) SetKeys(v []string) {
	x.xxx_hidden_Keys = v
}

func (x *GetManyRequest) SetPrefix(v string) {
	x.xxx_hidden_Prefix = v
}

type GetManyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SyncId string
	Keys   []string
	Prefix string
}

func (b0 GetManyRequest_builder) Build() *GetManyRequest {
	m0 := &GetManyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SyncId = b.SyncId
	x.xxx_hidden_Keys = b.Keys
	x.xxx_hidden_Prefix = b.Prefix
	return m0
}

type GetManyResponse struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items           *[]*GetManyItem        `protobuf:"bytes,1,rep,name=items,proto3"`
	xxx_hidden_UnprocessedKeys []string               `protobuf:"bytes,2,rep,name=unprocessed_keys,json=unprocessedKeys,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetManyResponse) Reset() {
	*x = GetManyResponse{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManyResponse) ProtoMessage() {}

func (x *GetManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetManyResponse) GetItems() []*GetManyItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *GetManyResponse) GetUnprocessedKeys() []string {
	if x != nil {
		return x.xxx_hidden_UnprocessedKeys
	}
	return nil
}

func (x *GetManyResponse) SetItems(v []*GetManyItem) {
	x.xxx_hidden_Items = &v
}

func (x *GetManyResponse) SetUnprocessedKeys(v []string) {
	x.xxx_hidden_UnprocessedKeys = v
}

type GetManyResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items           []*GetManyItem
	UnprocessedKeys []string
}

func (b0 GetManyResponse_builder) Build() *GetManyResponse {
	m0 := &GetManyResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_UnprocessedKeys = b.UnprocessedKeys
	return m0
}

type GetManyItem struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_Value []byte                 `protobuf:"bytes,2,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetManyItem) Reset() {
	*x = GetManyItem{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManyItem) ProtoMessage() {}

func (x *GetManyItem) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetManyItem) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *GetManyItem) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *GetManyItem) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *GetManyItem) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
}

type GetManyItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   string
	Value []byte
}

func (b0 GetManyItem_builder) Build() *GetManyItem {
	m0 := &GetManyItem{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

type GetAllRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SyncId    string                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3"`
	xxx_hidden_PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3"`
	xxx_hidden_Prefix    string                 `protobuf:"bytes,3,opt,name=prefix,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAllRequest) GetSyncId() string {
	if x != nil {
		return x.xxx_hidden_SyncId
	}
	return ""
}

func (x *GetAllRequest) GetPageToken() string {
	if x != nil {
		return x.xxx_hidden_PageToken
	}
	return ""
}

func (x *GetAllRequest) GetPrefix() string {
	if x != nil {
		return x.xxx_hidden_Prefix
	}
	return ""
}

func (x *GetAllRequest) SetSyncId(v string) {
	x.xxx_hidden_SyncId = v
}

func (x *GetAllRequest) SetPageToken(v string) {
	x.xxx_hidden_PageToken = v
}

func (x *GetAllRequest) SetPrefix(v string) {
	x.xxx_hidden_Prefix = v
}

type GetAllRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SyncId    string
	PageToken string
	Prefix    string
}

func (b0 GetAllRequest_builder) Build() *GetAllRequest {
	m0 := &GetAllRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SyncId = b.SyncId
	x.xxx_hidden_PageToken = b.PageToken
	x.xxx_hidden_Prefix = b.Prefix
	return m0
}

type GetAllResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items     *[]*GetAllItem         `protobuf:"bytes,1,rep,name=items,proto3"`
	xxx_hidden_PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAllResponse) GetItems() []*GetAllItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *GetAllResponse) GetPageToken() string {
	if x != nil {
		return x.xxx_hidden_PageToken
	}
	return ""
}

func (x *GetAllResponse) SetItems(v []*GetAllItem) {
	x.xxx_hidden_Items = &v
}

func (x *GetAllResponse) SetPageToken(v string) {
	x.xxx_hidden_PageToken = v
}

type GetAllResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items     []*GetAllItem
	PageToken string
}

func (b0 GetAllResponse_builder) Build() *GetAllResponse {
	m0 := &GetAllResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_PageToken = b.PageToken
	return m0
}

type GetAllItem struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_Value []byte                 `protobuf:"bytes,2,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAllItem) Reset() {
	*x = GetAllItem{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItem) ProtoMessage() {}

func (x *GetAllItem) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAllItem) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *GetAllItem) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *GetAllItem) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *GetAllItem) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
}

type GetAllItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   string
	Value []byte
}

func (b0 GetAllItem_builder) Build() *GetAllItem {
	m0 := &GetAllItem{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

// 4MB for a single gRPC request is the default limit- divide by 100 (SetMany/GetMany max items) and add some padding for overhead.
type SetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SyncId string                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3"`
	xxx_hidden_Key    string                 `protobuf:"bytes,2,opt,name=key,proto3"`
	xxx_hidden_Value  []byte                 `protobuf:"bytes,3,opt,name=value,proto3"`
	xxx_hidden_Prefix string                 `protobuf:"bytes,4,opt,name=prefix,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetRequest) GetSyncId() string {
	if x != nil {
		return x.xxx_hidden_SyncId
	}
	return ""
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *SetRequest) GetPrefix() string {
	if x != nil {
		return x.xxx_hidden_Prefix
	}
	return ""
}

func (x *SetRequest) SetSyncId(v string) {
	x.xxx_hidden_SyncId = v
}

func (x *SetRequest) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *SetRequest) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
}

func (x *SetRequest) SetPrefix(v string) {
	x.xxx_hidden_Prefix = v
}

type SetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SyncId string
	Key    string
	Value  []byte
	Prefix string
}

func (b0 SetRequest_builder) Build() *SetRequest {
	m0 := &SetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SyncId = b.SyncId
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Prefix = b.Prefix
	return m0
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SetResponse_builder) Build() *SetResponse {
	m0 := &SetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SetManyRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SyncId string                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3"`
	xxx_hidden_Values map[string][]byte      `protobuf:"bytes,2,rep,name=values,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Prefix string                 `protobuf:"bytes,3,opt,name=prefix,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetManyRequest) Reset() {
	*x = SetManyRequest{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetManyRequest) ProtoMessage() {}

func (x *SetManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetManyRequest) GetSyncId() string {
	if x != nil {
		return x.xxx_hidden_SyncId
	}
	return ""
}

func (x *SetManyRequest) GetValues() map[string][]byte {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *SetManyRequest) GetPrefix() string {
	if x != nil {
		return x.xxx_hidden_Prefix
	}
	return ""
}

func (x *SetManyRequest) SetSyncId(v string) {
	x.xxx_hidden_SyncId = v
}

func (x *SetManyRequest) SetValues(v map[string][]byte) {
	x.xxx_hidden_Values = v
}

func (x *SetManyRequest) SetPrefix(v string) {
	x.xxx_hidden_Prefix = v
}

type SetManyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SyncId string
	Values map[string][]byte
	Prefix string
}

func (b0 SetManyRequest_builder) Build() *SetManyRequest {
	m0 := &SetManyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SyncId = b.SyncId
	x.xxx_hidden_Values = b.Values
	x.xxx_hidden_Prefix = b.Prefix
	return m0
}

type SetManyResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetManyResponse) Reset() {
	*x = SetManyResponse{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetManyResponse) ProtoMessage() {}

func (x *SetManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SetManyResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SetManyResponse_builder) Build() *SetManyResponse {
	m0 := &SetManyResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DeleteRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SyncId string                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3"`
	xxx_hidden_Key    string                 `protobuf:"bytes,2,opt,name=key,proto3"`
	xxx_hidden_Prefix string                 `protobuf:"bytes,3,opt,name=prefix,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRequest) GetSyncId() string {
	if x != nil {
		return x.xxx_hidden_SyncId
	}
	return ""
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *DeleteRequest) GetPrefix() string {
	if x != nil {
		return x.xxx_hidden_Prefix
	}
	return ""
}

func (x *DeleteRequest) SetSyncId(v string) {
	x.xxx_hidden_SyncId = v
}

func (x *DeleteRequest) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *DeleteRequest) SetPrefix(v string) {
	x.xxx_hidden_Prefix = v
}

type DeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SyncId string
	Key    string
	Prefix string
}

func (b0 DeleteRequest_builder) Build() *DeleteRequest {
	m0 := &DeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SyncId = b.SyncId
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Prefix = b.Prefix
	return m0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteResponse_builder) Build() *DeleteResponse {
	m0 := &DeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DeleteManyRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SyncId string                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3"`
	xxx_hidden_Keys   []string               `protobuf:"bytes,2,rep,name=keys,proto3"`
	xxx_hidden_Prefix string                 `protobuf:"bytes,3,opt,name=prefix,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteManyRequest) Reset() {
	*x = DeleteManyRequest{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManyRequest) ProtoMessage() {}

func (x *DeleteManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteManyRequest) GetSyncId() string {
	if x != nil {
		return x.xxx_hidden_SyncId
	}
	return ""
}

func (x *DeleteManyRequest) GetKeys() []string {
	if x != nil {
		return x.xxx_hidden_Keys
	}
	return nil
}

func (x *DeleteManyRequest) GetPrefix() string {
	if x != nil {
		return x.xxx_hidden_Prefix
	}
	return ""
}

func (x *DeleteManyRequest) SetSyncId(v string) {
	x.xxx_hidden_SyncId = v
}

func (x *DeleteManyRequest) SetKeys(v []string) {
	x.xxx_hidden_Keys = v
}

func (x *DeleteManyRequest) SetPrefix(v string) {
	x.xxx_hidden_Prefix = v
}

type DeleteManyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SyncId string
	Keys   []string
	Prefix string
}

func (b0 DeleteManyRequest_builder) Build() *DeleteManyRequest {
	m0 := &DeleteManyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SyncId = b.SyncId
	x.xxx_hidden_Keys = b.Keys
	x.xxx_hidden_Prefix = b.Prefix
	return m0
}

type DeleteManyResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManyResponse) Reset() {
	*x = DeleteManyResponse{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManyResponse) ProtoMessage() {}

func (x *DeleteManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteManyResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteManyResponse_builder) Build() *DeleteManyResponse {
	m0 := &DeleteManyResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ClearRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SyncId string                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3"`
	xxx_hidden_Prefix string                 `protobuf:"bytes,2,opt,name=prefix,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClearRequest) GetSyncId() string {
	if x != nil {
		return x.xxx_hidden_SyncId
	}
	return ""
}

func (x *ClearRequest) GetPrefix() string {
	if x != nil {
		return x.xxx_hidden_Prefix
	}
	return ""
}

func (x *ClearRequest) SetSyncId(v string) {
	x.xxx_hidden_SyncId = v
}

func (x *ClearRequest) SetPrefix(v string) {
	x.xxx_hidden_Prefix = v
}

type ClearRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SyncId string
	Prefix string
}

func (b0 ClearRequest_builder) Build() *ClearRequest {
	m0 := &ClearRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SyncId = b.SyncId
	x.xxx_hidden_Prefix = b.Prefix
	return m0
}

type ClearResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearResponse) Reset() {
	*x = ClearResponse{}
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResponse) ProtoMessage() {}

func (x *ClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_session_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ClearResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ClearResponse_builder) Build() *ClearResponse {
	m0 := &ClearResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_c1_connectorapi_baton_v1_session_proto protoreflect.FileDescriptor

const file_c1_connectorapi_baton_v1_session_proto_rawDesc = "" +
	"\n" +
	"&c1/connectorapi/baton/v1/session.proto\x12\x18c1.connectorapi.baton.v1\x1a\x17validate/validate.proto\"\x7f\n" +
	"\n" +
	"GetRequest\x121\n" +
	"\async_id\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^[a-zA-Z0-9]{27}$R\x06syncId\x12\x1c\n" +
	"\x03key\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x02R\x03key\x12 \n" +
	"\x06prefix\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\x80\x02R\x06prefix\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x90\x01\n" +
	"\x0eGetManyRequest\x121\n" +
	"\async_id\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^[a-zA-Z0-9]{27}$R\x06syncId\x12)\n" +
	"\x04keys\x18\x02 \x03(\tB\x15\xfaB\x12\x92\x01\x0f\b\x01\x10d\x18\x01\"\ar\x05\x10\x01\x18\x80\x02R\x04keys\x12 \n" +
	"\x06prefix\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\x80\x02R\x06prefix\"y\n" +
	"\x0fGetManyResponse\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.c1.connectorapi.baton.v1.GetManyItemR\x05items\x12)\n" +
	"\x10unprocessed_keys\x18\x02 \x03(\tR\x0funprocessedKeys\"5\n" +
	"\vGetManyItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x83\x01\n" +
	"\rGetAllRequest\x121\n" +
	"\async_id\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^[a-zA-Z0-9]{27}$R\x06syncId\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12 \n" +
	"\x06prefix\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\x80\x02R\x06prefix\"k\n" +
	"\x0eGetAllResponse\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.c1.connectorapi.baton.v1.GetAllItemR\x05items\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"4\n" +
	"\n" +
	"GetAllItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xa3\x01\n" +
	"\n" +
	"SetRequest\x121\n" +
	"\async_id\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^[a-zA-Z0-9]{27}$R\x06syncId\x12\x1c\n" +
	"\x03key\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x02R\x03key\x12\"\n" +
	"\x05value\x18\x03 \x01(\fB\f\xfaB\tz\a\x10\x00\x18\x80\xe8\xfd\x01R\x05value\x12 \n" +
	"\x06prefix\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x18\x80\x02R\x06prefix\"\r\n" +
	"\vSetResponse\"\x8e\x02\n" +
	"\x0eSetManyRequest\x121\n" +
	"\async_id\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^[a-zA-Z0-9]{27}$R\x06syncId\x12l\n" +
	"\x06values\x18\x02 \x03(\v24.c1.connectorapi.baton.v1.SetManyRequest.ValuesEntryB\x1e\xfaB\x1b\x9a\x01\x18\b\x01\x10d\"\ar\x05\x10\x01\x18\x80\x02*\tz\a\x10\x00\x18\x80\xe8\xfd\x01R\x06values\x12 \n" +
	"\x06prefix\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\x80\x02R\x06prefix\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x11\n" +
	"\x0fSetManyResponse\"\x82\x01\n" +
	"\rDeleteRequest\x121\n" +
	"\async_id\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^[a-zA-Z0-9]{27}$R\x06syncId\x12\x1c\n" +
	"\x03key\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x02R\x03key\x12 \n" +
	"\x06prefix\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\x80\x02R\x06prefix\"\x10\n" +
	"\x0eDeleteResponse\"\x92\x01\n" +
	"\x11DeleteManyRequest\x121\n" +
	"\async_id\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^[a-zA-Z0-9]{27}$R\x06syncId\x12(\n" +
	"\x04keys\x18\x02 \x03(\tB\x14\xfaB\x11\x92\x01\x0e\b\x01\x10\xc8\x01\"\ar\x05\x10\x01\x18\x80\x02R\x04keys\x12 \n" +
	"\x06prefix\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\x80\x02R\x06prefix\"\x14\n" +
	"\x12DeleteManyResponse\"c\n" +
	"\fClearRequest\x121\n" +
	"\async_id\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^[a-zA-Z0-9]{27}$R\x06syncId\x12 \n" +
	"\x06prefix\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x18\x80\x02R\x06prefix\"\x0f\n" +
	"\rClearResponse2\x8a\x06\n" +
	"\x13BatonSessionService\x12T\n" +
	"\x03Get\x12$.c1.connectorapi.baton.v1.GetRequest\x1a%.c1.connectorapi.baton.v1.GetResponse\"\x00\x12`\n" +
	"\aGetMany\x12(.c1.connectorapi.baton.v1.GetManyRequest\x1a).c1.connectorapi.baton.v1.GetManyResponse\"\x00\x12]\n" +
	"\x06GetAll\x12'.c1.connectorapi.baton.v1.GetAllRequest\x1a(.c1.connectorapi.baton.v1.GetAllResponse\"\x00\x12T\n" +
	"\x03Set\x12$.c1.connectorapi.baton.v1.SetRequest\x1a%.c1.connectorapi.baton.v1.SetResponse\"\x00\x12`\n" +
	"\aSetMany\x12(.c1.connectorapi.baton.v1.SetManyRequest\x1a).c1.connectorapi.baton.v1.SetManyResponse\"\x00\x12]\n" +
	"\x06Delete\x12'.c1.connectorapi.baton.v1.DeleteRequest\x1a(.c1.connectorapi.baton.v1.DeleteResponse\"\x00\x12i\n" +
	"\n" +
	"DeleteMany\x12+.c1.connectorapi.baton.v1.DeleteManyRequest\x1a,.c1.connectorapi.baton.v1.DeleteManyResponse\"\x00\x12Z\n" +
	"\x05Clear\x12&.c1.connectorapi.baton.v1.ClearRequest\x1a'.c1.connectorapi.baton.v1.ClearResponse\"\x00B7Z5gitlab.com/ductone/c1/pkg/pb/c1/connectorapi/baton/v1b\x06proto3"

var file_c1_connectorapi_baton_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_c1_connectorapi_baton_v1_session_proto_goTypes = []any{
	(*GetRequest)(nil),         // 0: c1.connectorapi.baton.v1.GetRequest
	(*GetResponse)(nil),        // 1: c1.connectorapi.baton.v1.GetResponse
	(*GetManyRequest)(nil),     // 2: c1.connectorapi.baton.v1.GetManyRequest
	(*GetManyResponse)(nil),    // 3: c1.connectorapi.baton.v1.GetManyResponse
	(*GetManyItem)(nil),        // 4: c1.connectorapi.baton.v1.GetManyItem
	(*GetAllRequest)(nil),      // 5: c1.connectorapi.baton.v1.GetAllRequest
	(*GetAllResponse)(nil),     // 6: c1.connectorapi.baton.v1.GetAllResponse
	(*GetAllItem)(nil),         // 7: c1.connectorapi.baton.v1.GetAllItem
	(*SetRequest)(nil),         // 8: c1.connectorapi.baton.v1.SetRequest
	(*SetResponse)(nil),        // 9: c1.connectorapi.baton.v1.SetResponse
	(*SetManyRequest)(nil),     // 10: c1.connectorapi.baton.v1.SetManyRequest
	(*SetManyResponse)(nil),    // 11: c1.connectorapi.baton.v1.SetManyResponse
	(*DeleteRequest)(nil),      // 12: c1.connectorapi.baton.v1.DeleteRequest
	(*DeleteResponse)(nil),     // 13: c1.connectorapi.baton.v1.DeleteResponse
	(*DeleteManyRequest)(nil),  // 14: c1.connectorapi.baton.v1.DeleteManyRequest
	(*DeleteManyResponse)(nil), // 15: c1.connectorapi.baton.v1.DeleteManyResponse
	(*ClearRequest)(nil),       // 16: c1.connectorapi.baton.v1.ClearRequest
	(*ClearResponse)(nil),      // 17: c1.connectorapi.baton.v1.ClearResponse
	nil,                        // 18: c1.connectorapi.baton.v1.SetManyRequest.ValuesEntry
}
var file_c1_connectorapi_baton_v1_session_proto_depIdxs = []int32{
	4,  // 0: c1.connectorapi.baton.v1.GetManyResponse.items:type_name -> c1.connectorapi.baton.v1.GetManyItem
	7,  // 1: c1.connectorapi.baton.v1.GetAllResponse.items:type_name -> c1.connectorapi.baton.v1.GetAllItem
	18, // 2: c1.connectorapi.baton.v1.SetManyRequest.values:type_name -> c1.connectorapi.baton.v1.SetManyRequest.ValuesEntry
	0,  // 3: c1.connectorapi.baton.v1.BatonSessionService.Get:input_type -> c1.connectorapi.baton.v1.GetRequest
	2,  // 4: c1.connectorapi.baton.v1.BatonSessionService.GetMany:input_type -> c1.connectorapi.baton.v1.GetManyRequest
	5,  // 5: c1.connectorapi.baton.v1.BatonSessionService.GetAll:input_type -> c1.connectorapi.baton.v1.GetAllRequest
	8,  // 6: c1.connectorapi.baton.v1.BatonSessionService.Set:input_type -> c1.connectorapi.baton.v1.SetRequest
	10, // 7: c1.connectorapi.baton.v1.BatonSessionService.SetMany:input_type -> c1.connectorapi.baton.v1.SetManyRequest
	12, // 8: c1.connectorapi.baton.v1.BatonSessionService.Delete:input_type -> c1.connectorapi.baton.v1.DeleteRequest
	14, // 9: c1.connectorapi.baton.v1.BatonSessionService.DeleteMany:input_type -> c1.connectorapi.baton.v1.DeleteManyRequest
	16, // 10: c1.connectorapi.baton.v1.BatonSessionService.Clear:input_type -> c1.connectorapi.baton.v1.ClearRequest
	1,  // 11: c1.connectorapi.baton.v1.BatonSessionService.Get:output_type -> c1.connectorapi.baton.v1.GetResponse
	3,  // 12: c1.connectorapi.baton.v1.BatonSessionService.GetMany:output_type -> c1.connectorapi.baton.v1.GetManyResponse
	6,  // 13: c1.connectorapi.baton.v1.BatonSessionService.GetAll:output_type -> c1.connectorapi.baton.v1.GetAllResponse
	9,  // 14: c1.connectorapi.baton.v1.BatonSessionService.Set:output_type -> c1.connectorapi.baton.v1.SetResponse
	11, // 15: c1.connectorapi.baton.v1.BatonSessionService.SetMany:output_type -> c1.connectorapi.baton.v1.SetManyResponse
	13, // 16: c1.connectorapi.baton.v1.BatonSessionService.Delete:output_type -> c1.connectorapi.baton.v1.DeleteResponse
	15, // 17: c1.connectorapi.baton.v1.BatonSessionService.DeleteMany:output_type -> c1.connectorapi.baton.v1.DeleteManyResponse
	17, // 18: c1.connectorapi.baton.v1.BatonSessionService.Clear:output_type -> c1.connectorapi.baton.v1.ClearResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_c1_connectorapi_baton_v1_session_proto_init() }
func file_c1_connectorapi_baton_v1_session_proto_init() {
	if File_c1_connectorapi_baton_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c1_connectorapi_baton_v1_session_proto_rawDesc), len(file_c1_connectorapi_baton_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_c1_connectorapi_baton_v1_session_proto_goTypes,
		DependencyIndexes: file_c1_connectorapi_baton_v1_session_proto_depIdxs,
		MessageInfos:      file_c1_connectorapi_baton_v1_session_proto_msgTypes,
	}.Build()
	File_c1_connectorapi_baton_v1_session_proto = out.File
	file_c1_connectorapi_baton_v1_session_proto_goTypes = nil
	file_c1_connectorapi_baton_v1_session_proto_depIdxs = nil
}
