// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: c1/connectorapi/baton/v1/source_cache.proto

//go:build protoopaque

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RowKind  string                 `protobuf:"bytes,1,opt,name=row_kind,json=rowKind,proto3"`
	xxx_hidden_ScopeKey string                 `protobuf:"bytes,2,opt,name=scope_key,json=scopeKey,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_c1_connectorapi_baton_v1_source_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_source_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LookupRequest) GetRowKind() string {
	if x != nil {
		return x.xxx_hidden_RowKind
	}
	return ""
}

func (x *LookupRequest) GetScopeKey() string {
	if x != nil {
		return x.xxx_hidden_ScopeKey
	}
	return ""
}

func (x *LookupRequest) SetRowKind(v string) {
	x.xxx_hidden_RowKind = v
}

func (x *LookupRequest) SetScopeKey(v string) {
	x.xxx_hidden_ScopeKey = v
}

type LookupRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Row kind: resources / entitlements / grants
	// (pkg/sourcecache.RowKind values). Entries are partitioned by row
	// kind, so one scope key can carry a different validator per kind.
	RowKind string
	// Connector-defined stable scope identifier (a stable identifier for the canonical scope
	// (often a hex hash; see pkg/sourcecache.HashScope). Opaque to the
	// parent; matched verbatim against the previous sync's source-cache
	// entries.
	ScopeKey string
}

func (b0 LookupRequest_builder) Build() *LookupRequest {
	m0 := &LookupRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RowKind = b.RowKind
	x.xxx_hidden_ScopeKey = b.ScopeKey
	return m0
}

type LookupResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Found          bool                   `protobuf:"varint,1,opt,name=found,proto3"`
	xxx_hidden_CacheValidator string                 `protobuf:"bytes,2,opt,name=cache_validator,json=cacheValidator,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_c1_connectorapi_baton_v1_source_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connectorapi_baton_v1_source_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LookupResponse) GetFound() bool {
	if x != nil {
		return x.xxx_hidden_Found
	}
	return false
}

func (x *LookupResponse) GetCacheValidator() string {
	if x != nil {
		return x.xxx_hidden_CacheValidator
	}
	return ""
}

func (x *LookupResponse) SetFound(v bool) {
	x.xxx_hidden_Found = v
}

func (x *LookupResponse) SetCacheValidator(v string) {
	x.xxx_hidden_CacheValidator = v
}

type LookupResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// False means no prior entry exists for (row_kind, scope_key): the
	// connector must fetch fresh and must not emit SourceCacheReplay for
	// this scope.
	Found bool
	// The opaque validator the previous sync recorded for this scope (HTTP
	// ETag, delta token, ...). Empty when found is false. The cap is a
	// sanity bound sized for Microsoft Graph delta tokens, which are known
	// to run to thousands of characters; storage imposes no limit.
	CacheValidator string
}

func (b0 LookupResponse_builder) Build() *LookupResponse {
	m0 := &LookupResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Found = b.Found
	x.xxx_hidden_CacheValidator = b.CacheValidator
	return m0
}

var File_c1_connectorapi_baton_v1_source_cache_proto protoreflect.FileDescriptor

const file_c1_connectorapi_baton_v1_source_cache_proto_rawDesc = "" +
	"\n" +
	"+c1/connectorapi/baton/v1/source_cache.proto\x12\x18c1.connectorapi.baton.v1\x1a\x17validate/validate.proto\"^\n" +
	"\rLookupRequest\x12$\n" +
	"\brow_kind\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\arowKind\x12'\n" +
	"\tscope_key\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x02R\bscopeKey\"Z\n" +
	"\x0eLookupResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x122\n" +
	"\x0fcache_validator\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x18\x80\x80\x04R\x0ecacheValidator2x\n" +
	"\x17BatonSourceCacheService\x12]\n" +
	"\x06Lookup\x12'.c1.connectorapi.baton.v1.LookupRequest\x1a(.c1.connectorapi.baton.v1.LookupResponse\"\x00B7Z5gitlab.com/ductone/c1/pkg/pb/c1/connectorapi/baton/v1b\x06proto3"

var file_c1_connectorapi_baton_v1_source_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_c1_connectorapi_baton_v1_source_cache_proto_goTypes = []any{
	(*LookupRequest)(nil),  // 0: c1.connectorapi.baton.v1.LookupRequest
	(*LookupResponse)(nil), // 1: c1.connectorapi.baton.v1.LookupResponse
}
var file_c1_connectorapi_baton_v1_source_cache_proto_depIdxs = []int32{
	0, // 0: c1.connectorapi.baton.v1.BatonSourceCacheService.Lookup:input_type -> c1.connectorapi.baton.v1.LookupRequest
	1, // 1: c1.connectorapi.baton.v1.BatonSourceCacheService.Lookup:output_type -> c1.connectorapi.baton.v1.LookupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_c1_connectorapi_baton_v1_source_cache_proto_init() }
func file_c1_connectorapi_baton_v1_source_cache_proto_init() {
	if File_c1_connectorapi_baton_v1_source_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c1_connectorapi_baton_v1_source_cache_proto_rawDesc), len(file_c1_connectorapi_baton_v1_source_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_c1_connectorapi_baton_v1_source_cache_proto_goTypes,
		DependencyIndexes: file_c1_connectorapi_baton_v1_source_cache_proto_depIdxs,
		MessageInfos:      file_c1_connectorapi_baton_v1_source_cache_proto_msgTypes,
	}.Build()
	File_c1_connectorapi_baton_v1_source_cache_proto = out.File
	file_c1_connectorapi_baton_v1_source_cache_proto_goTypes = nil
	file_c1_connectorapi_baton_v1_source_cache_proto_depIdxs = nil
}
