// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: c1/reader/v2/sync.proto

//go:build protoopaque

package v2

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRun struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_StartedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3"`
	xxx_hidden_EndedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ended_at,json=endedAt,proto3"`
	xxx_hidden_SyncToken    string                 `protobuf:"bytes,4,opt,name=sync_token,json=syncToken,proto3"`
	xxx_hidden_SyncType     string                 `protobuf:"bytes,5,opt,name=sync_type,json=syncType,proto3"`
	xxx_hidden_ParentSyncId string                 `protobuf:"bytes,6,opt,name=parent_sync_id,json=parentSyncId,proto3"`
	xxx_hidden_Stats        *SyncStats             `protobuf:"bytes,7,opt,name=stats,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SyncRun) Reset() {
	*x = SyncRun{}
	mi := &file_c1_reader_v2_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRun) ProtoMessage() {}

func (x *SyncRun) ProtoReflect() protoreflect.Message {
	mi := &file_c1_reader_v2_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncRun) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *SyncRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartedAt
	}
	return nil
}

func (x *SyncRun) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EndedAt
	}
	return nil
}

func (x *SyncRun) GetSyncToken() string {
	if x != nil {
		return x.xxx_hidden_SyncToken
	}
	return ""
}

func (x *SyncRun) GetSyncType() string {
	if x != nil {
		return x.xxx_hidden_SyncType
	}
	return ""
}

func (x *SyncRun) GetParentSyncId() string {
	if x != nil {
		return x.xxx_hidden_ParentSyncId
	}
	return ""
}

func (x *SyncRun) GetStats() *SyncStats {
	if x != nil {
		return x.xxx_hidden_Stats
	}
	return nil
}

func (x *SyncRun) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *SyncRun) SetStartedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartedAt = v
}

func (x *SyncRun) SetEndedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_EndedAt = v
}

func (x *SyncRun) SetSyncToken(v string) {
	x.xxx_hidden_SyncToken = v
}

func (x *SyncRun) SetSyncType(v string) {
	x.xxx_hidden_SyncType = v
}

func (x *SyncRun) SetParentSyncId(v string) {
	x.xxx_hidden_ParentSyncId = v
}

func (x *SyncRun) SetStats(v *SyncStats) {
	x.xxx_hidden_Stats = v
}

func (x *SyncRun) HasStartedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartedAt != nil
}

func (x *SyncRun) HasEndedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EndedAt != nil
}

func (x *SyncRun) HasStats() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Stats != nil
}

func (x *SyncRun) ClearStartedAt() {
	x.xxx_hidden_StartedAt = nil
}

func (x *SyncRun) ClearEndedAt() {
	x.xxx_hidden_EndedAt = nil
}

func (x *SyncRun) ClearStats() {
	x.xxx_hidden_Stats = nil
}

type SyncRun_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id           string
	StartedAt    *timestamppb.Timestamp
	EndedAt      *timestamppb.Timestamp
	SyncToken    string
	SyncType     string
	ParentSyncId string
	Stats        *SyncStats
}

func (b0 SyncRun_builder) Build() *SyncRun {
	m0 := &SyncRun{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_StartedAt = b.StartedAt
	x.xxx_hidden_EndedAt = b.EndedAt
	x.xxx_hidden_SyncToken = b.SyncToken
	x.xxx_hidden_SyncType = b.SyncType
	x.xxx_hidden_ParentSyncId = b.ParentSyncId
	x.xxx_hidden_Stats = b.Stats
	return m0
}

type SyncStats struct {
	state                                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResourceTypes              int64                  `protobuf:"varint,1,opt,name=resource_types,json=resourceTypes,proto3"`
	xxx_hidden_Resources                  int64                  `protobuf:"varint,2,opt,name=resources,proto3"`
	xxx_hidden_Entitlements               int64                  `protobuf:"varint,3,opt,name=entitlements,proto3"`
	xxx_hidden_Grants                     int64                  `protobuf:"varint,4,opt,name=grants,proto3"`
	xxx_hidden_ResourcesByResourceType    map[string]int64       `protobuf:"bytes,5,rep,name=resources_by_resource_type,json=resourcesByResourceType,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	xxx_hidden_GrantsByResourceType       map[string]int64       `protobuf:"bytes,6,rep,name=grants_by_resource_type,json=grantsByResourceType,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	xxx_hidden_EntitlementsByResourceType map[string]int64       `protobuf:"bytes,7,rep,name=entitlements_by_resource_type,json=entitlementsByResourceType,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	xxx_hidden_Assets                     int64                  `protobuf:"varint,8,opt,name=assets,proto3"`
	xxx_hidden_StepDurationsMs            map[string]int64       `protobuf:"bytes,9,rep,name=step_durations_ms,json=stepDurationsMs,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	xxx_hidden_ConnectorCallStats         map[string]*CallStat   `protobuf:"bytes,10,rep,name=connector_call_stats,json=connectorCallStats,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_SessionStoreStats          map[string]*CallStat   `protobuf:"bytes,11,rep,name=session_store_stats,json=sessionStoreStats,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *SyncStats) Reset() {
	*x = SyncStats{}
	mi := &file_c1_reader_v2_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStats) ProtoMessage() {}

func (x *SyncStats) ProtoReflect() protoreflect.Message {
	mi := &file_c1_reader_v2_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncStats) GetResourceTypes() int64 {
	if x != nil {
		return x.xxx_hidden_ResourceTypes
	}
	return 0
}

func (x *SyncStats) GetResources() int64 {
	if x != nil {
		return x.xxx_hidden_Resources
	}
	return 0
}

func (x *SyncStats) GetEntitlements() int64 {
	if x != nil {
		return x.xxx_hidden_Entitlements
	}
	return 0
}

func (x *SyncStats) GetGrants() int64 {
	if x != nil {
		return x.xxx_hidden_Grants
	}
	return 0
}

func (x *SyncStats) GetResourcesByResourceType() map[string]int64 {
	if x != nil {
		return x.xxx_hidden_ResourcesByResourceType
	}
	return nil
}

func (x *SyncStats) GetGrantsByResourceType() map[string]int64 {
	if x != nil {
		return x.xxx_hidden_GrantsByResourceType
	}
	return nil
}

func (x *SyncStats) GetEntitlementsByResourceType() map[string]int64 {
	if x != nil {
		return x.xxx_hidden_EntitlementsByResourceType
	}
	return nil
}

func (x *SyncStats) GetAssets() int64 {
	if x != nil {
		return x.xxx_hidden_Assets
	}
	return 0
}

func (x *SyncStats) GetStepDurationsMs() map[string]int64 {
	if x != nil {
		return x.xxx_hidden_StepDurationsMs
	}
	return nil
}

func (x *SyncStats) GetConnectorCallStats() map[string]*CallStat {
	if x != nil {
		return x.xxx_hidden_ConnectorCallStats
	}
	return nil
}

func (x *SyncStats) GetSessionStoreStats() map[string]*CallStat {
	if x != nil {
		return x.xxx_hidden_SessionStoreStats
	}
	return nil
}

func (x *SyncStats) SetResourceTypes(v int64) {
	x.xxx_hidden_ResourceTypes = v
}

func (x *SyncStats) SetResources(v int64) {
	x.xxx_hidden_Resources = v
}

func (x *SyncStats) SetEntitlements(v int64) {
	x.xxx_hidden_Entitlements = v
}

func (x *SyncStats) SetGrants(v int64) {
	x.xxx_hidden_Grants = v
}

func (x *SyncStats) SetResourcesByResourceType(v map[string]int64) {
	x.xxx_hidden_ResourcesByResourceType = v
}

func (x *SyncStats) SetGrantsByResourceType(v map[string]int64) {
	x.xxx_hidden_GrantsByResourceType = v
}

func (x *SyncStats) SetEntitlementsByResourceType(v map[string]int64) {
	x.xxx_hidden_EntitlementsByResourceType = v
}

func (x *SyncStats) SetAssets(v int64) {
	x.xxx_hidden_Assets = v
}

func (x *SyncStats) SetStepDurationsMs(v map[string]int64) {
	x.xxx_hidden_StepDurationsMs = v
}

func (x *SyncStats) SetConnectorCallStats(v map[string]*CallStat) {
	x.xxx_hidden_ConnectorCallStats = v
}

func (x *SyncStats) SetSessionStoreStats(v map[string]*CallStat) {
	x.xxx_hidden_SessionStoreStats = v
}

type SyncStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResourceTypes              int64
	Resources                  int64
	Entitlements               int64
	Grants                     int64
	ResourcesByResourceType    map[string]int64
	GrantsByResourceType       map[string]int64
	EntitlementsByResourceType map[string]int64
	Assets                     int64
	// Timing / call stats lifted from the syncer token at EndSync.
	// Keys match the sync-token JSON fields (e.g. "rate_limit_wait",
	// "list-grants", "get"). Compacted syncs fold partial timings into
	// the token's top-level maps at compaction time.
	StepDurationsMs    map[string]int64
	ConnectorCallStats map[string]*CallStat
	SessionStoreStats  map[string]*CallStat
}

func (b0 SyncStats_builder) Build() *SyncStats {
	m0 := &SyncStats{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResourceTypes = b.ResourceTypes
	x.xxx_hidden_Resources = b.Resources
	x.xxx_hidden_Entitlements = b.Entitlements
	x.xxx_hidden_Grants = b.Grants
	x.xxx_hidden_ResourcesByResourceType = b.ResourcesByResourceType
	x.xxx_hidden_GrantsByResourceType = b.GrantsByResourceType
	x.xxx_hidden_EntitlementsByResourceType = b.EntitlementsByResourceType
	x.xxx_hidden_Assets = b.Assets
	x.xxx_hidden_StepDurationsMs = b.StepDurationsMs
	x.xxx_hidden_ConnectorCallStats = b.ConnectorCallStats
	x.xxx_hidden_SessionStoreStats = b.SessionStoreStats
	return m0
}

// CallStat is a cumulative latency / outcome counter for one named
// operation (a connector RPC method or a session-store op). Errors and
// Timeouts are populated for session-store stats; connector call stats
// leave them at zero.
type CallStat struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Count    int64                  `protobuf:"varint,1,opt,name=count,proto3"`
	xxx_hidden_TotalMs  int64                  `protobuf:"varint,2,opt,name=total_ms,json=totalMs,proto3"`
	xxx_hidden_MaxMs    int64                  `protobuf:"varint,3,opt,name=max_ms,json=maxMs,proto3"`
	xxx_hidden_Errors   int64                  `protobuf:"varint,4,opt,name=errors,proto3"`
	xxx_hidden_Timeouts int64                  `protobuf:"varint,5,opt,name=timeouts,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CallStat) Reset() {
	*x = CallStat{}
	mi := &file_c1_reader_v2_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallStat) ProtoMessage() {}

func (x *CallStat) ProtoReflect() protoreflect.Message {
	mi := &file_c1_reader_v2_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CallStat) GetCount() int64 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *CallStat) GetTotalMs() int64 {
	if x != nil {
		return x.xxx_hidden_TotalMs
	}
	return 0
}

func (x *CallStat) GetMaxMs() int64 {
	if x != nil {
		return x.xxx_hidden_MaxMs
	}
	return 0
}

func (x *CallStat) GetErrors() int64 {
	if x != nil {
		return x.xxx_hidden_Errors
	}
	return 0
}

func (x *CallStat) GetTimeouts() int64 {
	if x != nil {
		return x.xxx_hidden_Timeouts
	}
	return 0
}

func (x *CallStat) SetCount(v int64) {
	x.xxx_hidden_Count = v
}

func (x *CallStat) SetTotalMs(v int64) {
	x.xxx_hidden_TotalMs = v
}

func (x *CallStat) SetMaxMs(v int64) {
	x.xxx_hidden_MaxMs = v
}

func (x *CallStat) SetErrors(v int64) {
	x.xxx_hidden_Errors = v
}

func (x *CallStat) SetTimeouts(v int64) {
	x.xxx_hidden_Timeouts = v
}

type CallStat_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Count    int64
	TotalMs  int64
	MaxMs    int64
	Errors   int64
	Timeouts int64
}

func (b0 CallStat_builder) Build() *CallStat {
	m0 := &CallStat{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Count = b.Count
	x.xxx_hidden_TotalMs = b.TotalMs
	x.xxx_hidden_MaxMs = b.MaxMs
	x.xxx_hidden_Errors = b.Errors
	x.xxx_hidden_Timeouts = b.Timeouts
	return m0
}

type SyncsReaderServiceGetSyncRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SyncId      string                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3"`
	xxx_hidden_Annotations *[]*anypb.Any          `protobuf:"bytes,2,rep,name=annotations,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SyncsReaderServiceGetSyncRequest) Reset() {
	*x = SyncsReaderServiceGetSyncRequest{}
	mi := &file_c1_reader_v2_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncsReaderServiceGetSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncsReaderServiceGetSyncRequest) ProtoMessage() {}

func (x *SyncsReaderServiceGetSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c1_reader_v2_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncsReaderServiceGetSyncRequest) GetSyncId() string {
	if x != nil {
		return x.xxx_hidden_SyncId
	}
	return ""
}

func (x *SyncsReaderServiceGetSyncRequest) GetAnnotations() []*anypb.Any {
	if x != nil {
		if x.xxx_hidden_Annotations != nil {
			return *x.xxx_hidden_Annotations
		}
	}
	return nil
}

func (x *SyncsReaderServiceGetSyncRequest) SetSyncId(v string) {
	x.xxx_hidden_SyncId = v
}

func (x *SyncsReaderServiceGetSyncRequest) SetAnnotations(v []*anypb.Any) {
	x.xxx_hidden_Annotations = &v
}

type SyncsReaderServiceGetSyncRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SyncId      string
	Annotations []*anypb.Any
}

func (b0 SyncsReaderServiceGetSyncRequest_builder) Build() *SyncsReaderServiceGetSyncRequest {
	m0 := &SyncsReaderServiceGetSyncRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SyncId = b.SyncId
	x.xxx_hidden_Annotations = &b.Annotations
	return m0
}

type SyncsReaderServiceGetSyncResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sync        *SyncRun               `protobuf:"bytes,1,opt,name=sync,proto3"`
	xxx_hidden_Annotations *[]*anypb.Any          `protobuf:"bytes,2,rep,name=annotations,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SyncsReaderServiceGetSyncResponse) Reset() {
	*x = SyncsReaderServiceGetSyncResponse{}
	mi := &file_c1_reader_v2_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncsReaderServiceGetSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncsReaderServiceGetSyncResponse) ProtoMessage() {}

func (x *SyncsReaderServiceGetSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c1_reader_v2_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncsReaderServiceGetSyncResponse) GetSync() *SyncRun {
	if x != nil {
		return x.xxx_hidden_Sync
	}
	return nil
}

func (x *SyncsReaderServiceGetSyncResponse) GetAnnotations() []*anypb.Any {
	if x != nil {
		if x.xxx_hidden_Annotations != nil {
			return *x.xxx_hidden_Annotations
		}
	}
	return nil
}

func (x *SyncsReaderServiceGetSyncResponse) SetSync(v *SyncRun) {
	x.xxx_hidden_Sync = v
}

func (x *SyncsReaderServiceGetSyncResponse) SetAnnotations(v []*anypb.Any) {
	x.xxx_hidden_Annotations = &v
}

func (x *SyncsReaderServiceGetSyncResponse) HasSync() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sync != nil
}

func (x *SyncsReaderServiceGetSyncResponse) ClearSync() {
	x.xxx_hidden_Sync = nil
}

type SyncsReaderServiceGetSyncResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sync        *SyncRun
	Annotations []*anypb.Any
}

func (b0 SyncsReaderServiceGetSyncResponse_builder) Build() *SyncsReaderServiceGetSyncResponse {
	m0 := &SyncsReaderServiceGetSyncResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Sync = b.Sync
	x.xxx_hidden_Annotations = &b.Annotations
	return m0
}

type SyncsReaderServiceListSyncsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PageSize    uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3"`
	xxx_hidden_PageToken   string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3"`
	xxx_hidden_Annotations *[]*anypb.Any          `protobuf:"bytes,3,rep,name=annotations,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SyncsReaderServiceListSyncsRequest) Reset() {
	*x = SyncsReaderServiceListSyncsRequest{}
	mi := &file_c1_reader_v2_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncsReaderServiceListSyncsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncsReaderServiceListSyncsRequest) ProtoMessage() {}

func (x *SyncsReaderServiceListSyncsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c1_reader_v2_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncsReaderServiceListSyncsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *SyncsReaderServiceListSyncsRequest) GetPageToken() string {
	if x != nil {
		return x.xxx_hidden_PageToken
	}
	return ""
}

func (x *SyncsReaderServiceListSyncsRequest) GetAnnotations() []*anypb.Any {
	if x != nil {
		if x.xxx_hidden_Annotations != nil {
			return *x.xxx_hidden_Annotations
		}
	}
	return nil
}

func (x *SyncsReaderServiceListSyncsRequest) SetPageSize(v uint32) {
	x.xxx_hidden_PageSize = v
}

func (x *SyncsReaderServiceListSyncsRequest) SetPageToken(v string) {
	x.xxx_hidden_PageToken = v
}

func (x *SyncsReaderServiceListSyncsRequest) SetAnnotations(v []*anypb.Any) {
	x.xxx_hidden_Annotations = &v
}

type SyncsReaderServiceListSyncsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PageSize    uint32
	PageToken   string
	Annotations []*anypb.Any
}

func (b0 SyncsReaderServiceListSyncsRequest_builder) Build() *SyncsReaderServiceListSyncsRequest {
	m0 := &SyncsReaderServiceListSyncsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PageSize = b.PageSize
	x.xxx_hidden_PageToken = b.PageToken
	x.xxx_hidden_Annotations = &b.Annotations
	return m0
}

type SyncsReaderServiceListSyncsResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Syncs         *[]*SyncRun            `protobuf:"bytes,1,rep,name=syncs,proto3"`
	xxx_hidden_NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3"`
	xxx_hidden_Annotations   *[]*anypb.Any          `protobuf:"bytes,3,rep,name=annotations,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SyncsReaderServiceListSyncsResponse) Reset() {
	*x = SyncsReaderServiceListSyncsResponse{}
	mi := &file_c1_reader_v2_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncsReaderServiceListSyncsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncsReaderServiceListSyncsResponse) ProtoMessage() {}

func (x *SyncsReaderServiceListSyncsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c1_reader_v2_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncsReaderServiceListSyncsResponse) GetSyncs() []*SyncRun {
	if x != nil {
		if x.xxx_hidden_Syncs != nil {
			return *x.xxx_hidden_Syncs
		}
	}
	return nil
}

func (x *SyncsReaderServiceListSyncsResponse) GetNextPageToken() string {
	if x != nil {
		return x.xxx_hidden_NextPageToken
	}
	return ""
}

func (x *SyncsReaderServiceListSyncsResponse) GetAnnotations() []*anypb.Any {
	if x != nil {
		if x.xxx_hidden_Annotations != nil {
			return *x.xxx_hidden_Annotations
		}
	}
	return nil
}

func (x *SyncsReaderServiceListSyncsResponse) SetSyncs(v []*SyncRun) {
	x.xxx_hidden_Syncs = &v
}

func (x *SyncsReaderServiceListSyncsResponse) SetNextPageToken(v string) {
	x.xxx_hidden_NextPageToken = v
}

func (x *SyncsReaderServiceListSyncsResponse) SetAnnotations(v []*anypb.Any) {
	x.xxx_hidden_Annotations = &v
}

type SyncsReaderServiceListSyncsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Syncs         []*SyncRun
	NextPageToken string
	Annotations   []*anypb.Any
}

func (b0 SyncsReaderServiceListSyncsResponse_builder) Build() *SyncsReaderServiceListSyncsResponse {
	m0 := &SyncsReaderServiceListSyncsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Syncs = &b.Syncs
	x.xxx_hidden_NextPageToken = b.NextPageToken
	x.xxx_hidden_Annotations = &b.Annotations
	return m0
}

type SyncsReaderServiceGetLatestFinishedSyncRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Annotations *[]*anypb.Any          `protobuf:"bytes,1,rep,name=annotations,proto3"`
	xxx_hidden_SyncType    string                 `protobuf:"bytes,2,opt,name=sync_type,json=syncType,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SyncsReaderServiceGetLatestFinishedSyncRequest) Reset() {
	*x = SyncsReaderServiceGetLatestFinishedSyncRequest{}
	mi := &file_c1_reader_v2_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncsReaderServiceGetLatestFinishedSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncsReaderServiceGetLatestFinishedSyncRequest) ProtoMessage() {}

func (x *SyncsReaderServiceGetLatestFinishedSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_c1_reader_v2_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncsReaderServiceGetLatestFinishedSyncRequest) GetAnnotations() []*anypb.Any {
	if x != nil {
		if x.xxx_hidden_Annotations != nil {
			return *x.xxx_hidden_Annotations
		}
	}
	return nil
}

func (x *SyncsReaderServiceGetLatestFinishedSyncRequest) GetSyncType() string {
	if x != nil {
		return x.xxx_hidden_SyncType
	}
	return ""
}

func (x *SyncsReaderServiceGetLatestFinishedSyncRequest) SetAnnotations(v []*anypb.Any) {
	x.xxx_hidden_Annotations = &v
}

func (x *SyncsReaderServiceGetLatestFinishedSyncRequest) SetSyncType(v string) {
	x.xxx_hidden_SyncType = v
}

type SyncsReaderServiceGetLatestFinishedSyncRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Annotations []*anypb.Any
	SyncType    string
}

func (b0 SyncsReaderServiceGetLatestFinishedSyncRequest_builder) Build() *SyncsReaderServiceGetLatestFinishedSyncRequest {
	m0 := &SyncsReaderServiceGetLatestFinishedSyncRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Annotations = &b.Annotations
	x.xxx_hidden_SyncType = b.SyncType
	return m0
}

type SyncsReaderServiceGetLatestFinishedSyncResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sync        *SyncRun               `protobuf:"bytes,1,opt,name=sync,proto3"`
	xxx_hidden_Annotations *[]*anypb.Any          `protobuf:"bytes,2,rep,name=annotations,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SyncsReaderServiceGetLatestFinishedSyncResponse) Reset() {
	*x = SyncsReaderServiceGetLatestFinishedSyncResponse{}
	mi := &file_c1_reader_v2_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncsReaderServiceGetLatestFinishedSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncsReaderServiceGetLatestFinishedSyncResponse) ProtoMessage() {}

func (x *SyncsReaderServiceGetLatestFinishedSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c1_reader_v2_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncsReaderServiceGetLatestFinishedSyncResponse) GetSync() *SyncRun {
	if x != nil {
		return x.xxx_hidden_Sync
	}
	return nil
}

func (x *SyncsReaderServiceGetLatestFinishedSyncResponse) GetAnnotations() []*anypb.Any {
	if x != nil {
		if x.xxx_hidden_Annotations != nil {
			return *x.xxx_hidden_Annotations
		}
	}
	return nil
}

func (x *SyncsReaderServiceGetLatestFinishedSyncResponse) SetSync(v *SyncRun) {
	x.xxx_hidden_Sync = v
}

func (x *SyncsReaderServiceGetLatestFinishedSyncResponse) SetAnnotations(v []*anypb.Any) {
	x.xxx_hidden_Annotations = &v
}

func (x *SyncsReaderServiceGetLatestFinishedSyncResponse) HasSync() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sync != nil
}

func (x *SyncsReaderServiceGetLatestFinishedSyncResponse) ClearSync() {
	x.xxx_hidden_Sync = nil
}

type SyncsReaderServiceGetLatestFinishedSyncResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sync        *SyncRun
	Annotations []*anypb.Any
}

func (b0 SyncsReaderServiceGetLatestFinishedSyncResponse_builder) Build() *SyncsReaderServiceGetLatestFinishedSyncResponse {
	m0 := &SyncsReaderServiceGetLatestFinishedSyncResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Sync = b.Sync
	x.xxx_hidden_Annotations = &b.Annotations
	return m0
}

var File_c1_reader_v2_sync_proto protoreflect.FileDescriptor

const file_c1_reader_v2_sync_proto_rawDesc = "" +
	"\n" +
	"\x17c1/reader/v2/sync.proto\x12\fc1.reader.v2\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\x9c\x02\n" +
	"\aSyncRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x1d\n" +
	"\n" +
	"sync_token\x18\x04 \x01(\tR\tsyncToken\x12\x1b\n" +
	"\tsync_type\x18\x05 \x01(\tR\bsyncType\x12$\n" +
	"\x0eparent_sync_id\x18\x06 \x01(\tR\fparentSyncId\x12-\n" +
	"\x05stats\x18\a \x01(\v2\x17.c1.reader.v2.SyncStatsR\x05stats\"\xff\t\n" +
	"\tSyncStats\x12%\n" +
	"\x0eresource_types\x18\x01 \x01(\x03R\rresourceTypes\x12\x1c\n" +
	"\tresources\x18\x02 \x01(\x03R\tresources\x12\"\n" +
	"\fentitlements\x18\x03 \x01(\x03R\fentitlements\x12\x16\n" +
	"\x06grants\x18\x04 \x01(\x03R\x06grants\x12q\n" +
	"\x1aresources_by_resource_type\x18\x05 \x03(\v24.c1.reader.v2.SyncStats.ResourcesByResourceTypeEntryR\x17resourcesByResourceType\x12h\n" +
	"\x17grants_by_resource_type\x18\x06 \x03(\v21.c1.reader.v2.SyncStats.GrantsByResourceTypeEntryR\x14grantsByResourceType\x12z\n" +
	"\x1dentitlements_by_resource_type\x18\a \x03(\v27.c1.reader.v2.SyncStats.EntitlementsByResourceTypeEntryR\x1aentitlementsByResourceType\x12\x16\n" +
	"\x06assets\x18\b \x01(\x03R\x06assets\x12X\n" +
	"\x11step_durations_ms\x18\t \x03(\v2,.c1.reader.v2.SyncStats.StepDurationsMsEntryR\x0fstepDurationsMs\x12a\n" +
	"\x14connector_call_stats\x18\n" +
	" \x03(\v2/.c1.reader.v2.SyncStats.ConnectorCallStatsEntryR\x12connectorCallStats\x12^\n" +
	"\x13session_store_stats\x18\v \x03(\v2..c1.reader.v2.SyncStats.SessionStoreStatsEntryR\x11sessionStoreStats\x1aJ\n" +
	"\x1cResourcesByResourceTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aG\n" +
	"\x19GrantsByResourceTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aM\n" +
	"\x1fEntitlementsByResourceTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aB\n" +
	"\x14StepDurationsMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a]\n" +
	"\x17ConnectorCallStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.c1.reader.v2.CallStatR\x05value:\x028\x01\x1a\\\n" +
	"\x16SessionStoreStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.c1.reader.v2.CallStatR\x05value:\x028\x01\"\x86\x01\n" +
	"\bCallStat\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x19\n" +
	"\btotal_ms\x18\x02 \x01(\x03R\atotalMs\x12\x15\n" +
	"\x06max_ms\x18\x03 \x01(\x03R\x05maxMs\x12\x16\n" +
	"\x06errors\x18\x04 \x01(\x03R\x06errors\x12\x1a\n" +
	"\btimeouts\x18\x05 \x01(\x03R\btimeouts\"s\n" +
	" SyncsReaderServiceGetSyncRequest\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\x126\n" +
	"\vannotations\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\vannotations\"\x86\x01\n" +
	"!SyncsReaderServiceGetSyncResponse\x12)\n" +
	"\x04sync\x18\x01 \x01(\v2\x15.c1.reader.v2.SyncRunR\x04sync\x126\n" +
	"\vannotations\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\vannotations\"\xb3\x01\n" +
	"\"SyncsReaderServiceListSyncsRequest\x12'\n" +
	"\tpage_size\x18\x01 \x01(\rB\n" +
	"\xfaB\a*\x05\x18\xfa\x01@\x01R\bpageSize\x12,\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\r\xfaB\n" +
	"r\b \x01(\x80\x10\xd0\x01\x01R\tpageToken\x126\n" +
	"\vannotations\x18\x03 \x03(\v2\x14.google.protobuf.AnyR\vannotations\"\xc1\x01\n" +
	"#SyncsReaderServiceListSyncsResponse\x12+\n" +
	"\x05syncs\x18\x01 \x03(\v2\x15.c1.reader.v2.SyncRunR\x05syncs\x125\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\r\xfaB\n" +
	"r\b \x01(\x80\x10\xd0\x01\x01R\rnextPageToken\x126\n" +
	"\vannotations\x18\x03 \x03(\v2\x14.google.protobuf.AnyR\vannotations\"\x85\x01\n" +
	".SyncsReaderServiceGetLatestFinishedSyncRequest\x126\n" +
	"\vannotations\x18\x01 \x03(\v2\x14.google.protobuf.AnyR\vannotations\x12\x1b\n" +
	"\tsync_type\x18\x02 \x01(\tR\bsyncType\"\x94\x01\n" +
	"/SyncsReaderServiceGetLatestFinishedSyncResponse\x12)\n" +
	"\x04sync\x18\x01 \x01(\v2\x15.c1.reader.v2.SyncRunR\x04sync\x126\n" +
	"\vannotations\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\vannotations2\x89\x03\n" +
	"\x12SyncsReaderService\x12j\n" +
	"\aGetSync\x12..c1.reader.v2.SyncsReaderServiceGetSyncRequest\x1a/.c1.reader.v2.SyncsReaderServiceGetSyncResponse\x12p\n" +
	"\tListSyncs\x120.c1.reader.v2.SyncsReaderServiceListSyncsRequest\x1a1.c1.reader.v2.SyncsReaderServiceListSyncsResponse\x12\x94\x01\n" +
	"\x15GetLatestFinishedSync\x12<.c1.reader.v2.SyncsReaderServiceGetLatestFinishedSyncRequest\x1a=.c1.reader.v2.SyncsReaderServiceGetLatestFinishedSyncResponseB3Z1github.com/conductorone/baton-sdk/pb/c1/reader/v2b\x06proto3"

var file_c1_reader_v2_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_c1_reader_v2_sync_proto_goTypes = []any{
	(*SyncRun)(nil),                                         // 0: c1.reader.v2.SyncRun
	(*SyncStats)(nil),                                       // 1: c1.reader.v2.SyncStats
	(*CallStat)(nil),                                        // 2: c1.reader.v2.CallStat
	(*SyncsReaderServiceGetSyncRequest)(nil),                // 3: c1.reader.v2.SyncsReaderServiceGetSyncRequest
	(*SyncsReaderServiceGetSyncResponse)(nil),               // 4: c1.reader.v2.SyncsReaderServiceGetSyncResponse
	(*SyncsReaderServiceListSyncsRequest)(nil),              // 5: c1.reader.v2.SyncsReaderServiceListSyncsRequest
	(*SyncsReaderServiceListSyncsResponse)(nil),             // 6: c1.reader.v2.SyncsReaderServiceListSyncsResponse
	(*SyncsReaderServiceGetLatestFinishedSyncRequest)(nil),  // 7: c1.reader.v2.SyncsReaderServiceGetLatestFinishedSyncRequest
	(*SyncsReaderServiceGetLatestFinishedSyncResponse)(nil), // 8: c1.reader.v2.SyncsReaderServiceGetLatestFinishedSyncResponse
	nil,                           // 9: c1.reader.v2.SyncStats.ResourcesByResourceTypeEntry
	nil,                           // 10: c1.reader.v2.SyncStats.GrantsByResourceTypeEntry
	nil,                           // 11: c1.reader.v2.SyncStats.EntitlementsByResourceTypeEntry
	nil,                           // 12: c1.reader.v2.SyncStats.StepDurationsMsEntry
	nil,                           // 13: c1.reader.v2.SyncStats.ConnectorCallStatsEntry
	nil,                           // 14: c1.reader.v2.SyncStats.SessionStoreStatsEntry
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 16: google.protobuf.Any
}
var file_c1_reader_v2_sync_proto_depIdxs = []int32{
	15, // 0: c1.reader.v2.SyncRun.started_at:type_name -> google.protobuf.Timestamp
	15, // 1: c1.reader.v2.SyncRun.ended_at:type_name -> google.protobuf.Timestamp
	1,  // 2: c1.reader.v2.SyncRun.stats:type_name -> c1.reader.v2.SyncStats
	9,  // 3: c1.reader.v2.SyncStats.resources_by_resource_type:type_name -> c1.reader.v2.SyncStats.ResourcesByResourceTypeEntry
	10, // 4: c1.reader.v2.SyncStats.grants_by_resource_type:type_name -> c1.reader.v2.SyncStats.GrantsByResourceTypeEntry
	11, // 5: c1.reader.v2.SyncStats.entitlements_by_resource_type:type_name -> c1.reader.v2.SyncStats.EntitlementsByResourceTypeEntry
	12, // 6: c1.reader.v2.SyncStats.step_durations_ms:type_name -> c1.reader.v2.SyncStats.StepDurationsMsEntry
	13, // 7: c1.reader.v2.SyncStats.connector_call_stats:type_name -> c1.reader.v2.SyncStats.ConnectorCallStatsEntry
	14, // 8: c1.reader.v2.SyncStats.session_store_stats:type_name -> c1.reader.v2.SyncStats.SessionStoreStatsEntry
	16, // 9: c1.reader.v2.SyncsReaderServiceGetSyncRequest.annotations:type_name -> google.protobuf.Any
	0,  // 10: c1.reader.v2.SyncsReaderServiceGetSyncResponse.sync:type_name -> c1.reader.v2.SyncRun
	16, // 11: c1.reader.v2.SyncsReaderServiceGetSyncResponse.annotations:type_name -> google.protobuf.Any
	16, // 12: c1.reader.v2.SyncsReaderServiceListSyncsRequest.annotations:type_name -> google.protobuf.Any
	0,  // 13: c1.reader.v2.SyncsReaderServiceListSyncsResponse.syncs:type_name -> c1.reader.v2.SyncRun
	16, // 14: c1.reader.v2.SyncsReaderServiceListSyncsResponse.annotations:type_name -> google.protobuf.Any
	16, // 15: c1.reader.v2.SyncsReaderServiceGetLatestFinishedSyncRequest.annotations:type_name -> google.protobuf.Any
	0,  // 16: c1.reader.v2.SyncsReaderServiceGetLatestFinishedSyncResponse.sync:type_name -> c1.reader.v2.SyncRun
	16, // 17: c1.reader.v2.SyncsReaderServiceGetLatestFinishedSyncResponse.annotations:type_name -> google.protobuf.Any
	2,  // 18: c1.reader.v2.SyncStats.ConnectorCallStatsEntry.value:type_name -> c1.reader.v2.CallStat
	2,  // 19: c1.reader.v2.SyncStats.SessionStoreStatsEntry.value:type_name -> c1.reader.v2.CallStat
	3,  // 20: c1.reader.v2.SyncsReaderService.GetSync:input_type -> c1.reader.v2.SyncsReaderServiceGetSyncRequest
	5,  // 21: c1.reader.v2.SyncsReaderService.ListSyncs:input_type -> c1.reader.v2.SyncsReaderServiceListSyncsRequest
	7,  // 22: c1.reader.v2.SyncsReaderService.GetLatestFinishedSync:input_type -> c1.reader.v2.SyncsReaderServiceGetLatestFinishedSyncRequest
	4,  // 23: c1.reader.v2.SyncsReaderService.GetSync:output_type -> c1.reader.v2.SyncsReaderServiceGetSyncResponse
	6,  // 24: c1.reader.v2.SyncsReaderService.ListSyncs:output_type -> c1.reader.v2.SyncsReaderServiceListSyncsResponse
	8,  // 25: c1.reader.v2.SyncsReaderService.GetLatestFinishedSync:output_type -> c1.reader.v2.SyncsReaderServiceGetLatestFinishedSyncResponse
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_c1_reader_v2_sync_proto_init() }
func file_c1_reader_v2_sync_proto_init() {
	if File_c1_reader_v2_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c1_reader_v2_sync_proto_rawDesc), len(file_c1_reader_v2_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_c1_reader_v2_sync_proto_goTypes,
		DependencyIndexes: file_c1_reader_v2_sync_proto_depIdxs,
		MessageInfos:      file_c1_reader_v2_sync_proto_msgTypes,
	}.Build()
	File_c1_reader_v2_sync_proto = out.File
	file_c1_reader_v2_sync_proto_goTypes = nil
	file_c1_reader_v2_sync_proto_depIdxs = nil
}
