// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: c1/connector/v2/annotation_type_scoped_entitlements.proto

//go:build !protoopaque

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type-scoped entitlement ingestion.
//
// Some providers expose change/enumeration APIs whose natural unit is a
// whole collection (or a connector-defined shard of one), not a single
// resource — e.g. Microsoft Graph delta queries, where one stream yields
// entitlement definitions for up to 50 groups. Forcing that shape through
// the per-resource ListEntitlements fan-out costs one request per resource
// even when nothing changed.
//
// A resource type annotated with TypeScopedEntitlements is EXCLUDED from
// the per-resource entitlements fan-out. Instead the syncer issues
// ListEntitlements calls carrying this annotation on the REQUEST as the
// routing marker; the request's resource is a self-referential stub
// ({type, type} — wire validation requires a non-empty resource id and
// the stub identifies the type, never a real resource). The connector
// answers with entitlements for the whole type, across as many paginated
// cursors as it chooses to spawn (see EnqueuePageTokens in
// annotation_type_scoped_grants.proto).
//
// This is the entitlements-phase analogue of TypeScopedGrants: the
// connector takes over enumeration for the type, and every downstream
// behavior (storage, source-cache scopes/replay/tombstones, exclusion-
// group validation, rate limiting, page-token checkpointing) is unchanged
// because entitlements are self-describing rows.
//
// COMPLETENESS CONTRACT: a full sync of an annotated type must emit (or
// replay, via source-cache annotations) EVERY entitlement of that type.
// The syncer no longer visits each resource, so completeness rests
// entirely on the connector's enumeration.
//
// SKIP ANNOTATIONS: for an annotated type the syncer does not consult
// shouldSkipEntitlements on the type-scoped path. The connector owns skip
// semantics for resources of that type (omit rows; do not rely on
// per-resource SkipEntitlements* annotations to suppress the type-scoped
// call).
//
// ZERO-RESOURCE TYPES: the planner still enqueues the type-scoped action
// when the store holds no resources of the type. The connector must
// return an empty page (or EnqueuePageTokens that resolve empty), not an
// error — an empty type is a valid outcome.
//
// TARGETED SYNC: SyncTargetedResource must not enqueue a per-resource
// SyncEntitlementsOp for a type-scoped type. The type-scoped planner
// action is the only legal entitlements path; a targeted sync of one
// resource of an annotated type syncs the resource (and children) but
// leaves type-scoped entitlement enumeration to a full entitlements
// phase.
//
// ROUTING MARKER: TypeScopedEntitlements routes the ListEntitlements
// call; it implies no repair machinery of its own. It IS listed in the
// ingestion-invariant side-effect coverage map, covered by invariant I7
// (entitlement→resource referential integrity): type-granularity scopes
// can carry entitlement rows for resources that vanished between
// enumerations, and the post-collection check is what catches that.
type TypeScopedEntitlements struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeScopedEntitlements) Reset() {
	*x = TypeScopedEntitlements{}
	mi := &file_c1_connector_v2_annotation_type_scoped_entitlements_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeScopedEntitlements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeScopedEntitlements) ProtoMessage() {}

func (x *TypeScopedEntitlements) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connector_v2_annotation_type_scoped_entitlements_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TypeScopedEntitlements_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TypeScopedEntitlements_builder) Build() *TypeScopedEntitlements {
	m0 := &TypeScopedEntitlements{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_c1_connector_v2_annotation_type_scoped_entitlements_proto protoreflect.FileDescriptor

const file_c1_connector_v2_annotation_type_scoped_entitlements_proto_rawDesc = "" +
	"\n" +
	"9c1/connector/v2/annotation_type_scoped_entitlements.proto\x12\x0fc1.connector.v2\"\x18\n" +
	"\x16TypeScopedEntitlementsB6Z4github.com/conductorone/baton-sdk/pb/c1/connector/v2b\x06proto3"

var file_c1_connector_v2_annotation_type_scoped_entitlements_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_c1_connector_v2_annotation_type_scoped_entitlements_proto_goTypes = []any{
	(*TypeScopedEntitlements)(nil), // 0: c1.connector.v2.TypeScopedEntitlements
}
var file_c1_connector_v2_annotation_type_scoped_entitlements_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_c1_connector_v2_annotation_type_scoped_entitlements_proto_init() }
func file_c1_connector_v2_annotation_type_scoped_entitlements_proto_init() {
	if File_c1_connector_v2_annotation_type_scoped_entitlements_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c1_connector_v2_annotation_type_scoped_entitlements_proto_rawDesc), len(file_c1_connector_v2_annotation_type_scoped_entitlements_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c1_connector_v2_annotation_type_scoped_entitlements_proto_goTypes,
		DependencyIndexes: file_c1_connector_v2_annotation_type_scoped_entitlements_proto_depIdxs,
		MessageInfos:      file_c1_connector_v2_annotation_type_scoped_entitlements_proto_msgTypes,
	}.Build()
	File_c1_connector_v2_annotation_type_scoped_entitlements_proto = out.File
	file_c1_connector_v2_annotation_type_scoped_entitlements_proto_goTypes = nil
	file_c1_connector_v2_annotation_type_scoped_entitlements_proto_depIdxs = nil
}
