// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: c1/connector/v2/annotation_security_insight.proto

//go:build !protoopaque

package v2

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecurityInsightTrait is the trait annotation for resources with TRAIT_SECURITY_INSIGHT.
// It contains the metadata for the security insight including type, value, observation time,
// and the target entity (user or resource) that this insight should be bound to.
type SecurityInsightTrait struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The type of insight (e.g., "crowdstrike_zta_score", "wiz_critical_vulnerability")
	InsightType string `protobuf:"bytes,1,opt,name=insight_type,json=insightType,proto3" json:"insight_type,omitempty"`
	// The value of the insight (e.g., "85", "High", "Critical")
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// When this insight was observed/captured from the source system
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// Additional structured context (deep links, remediation steps, etc.)
	Context *structpb.Struct `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	// The target entity this insight should be bound to by Uplift
	//
	// Types that are valid to be assigned to Target:
	//
	//	*SecurityInsightTrait_User
	//	*SecurityInsightTrait_Resource
	Target        isSecurityInsightTrait_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityInsightTrait) Reset() {
	*x = SecurityInsightTrait{}
	mi := &file_c1_connector_v2_annotation_security_insight_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityInsightTrait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityInsightTrait) ProtoMessage() {}

func (x *SecurityInsightTrait) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connector_v2_annotation_security_insight_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecurityInsightTrait) GetInsightType() string {
	if x != nil {
		return x.InsightType
	}
	return ""
}

func (x *SecurityInsightTrait) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SecurityInsightTrait) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *SecurityInsightTrait) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SecurityInsightTrait) GetTarget() isSecurityInsightTrait_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *SecurityInsightTrait) GetUser() *SecurityInsightTrait_UserTarget {
	if x != nil {
		if x, ok := x.Target.(*SecurityInsightTrait_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *SecurityInsightTrait) GetResource() *SecurityInsightTrait_ResourceTarget {
	if x != nil {
		if x, ok := x.Target.(*SecurityInsightTrait_Resource); ok {
			return x.Resource
		}
	}
	return nil
}

func (x *SecurityInsightTrait) SetInsightType(v string) {
	x.InsightType = v
}

func (x *SecurityInsightTrait) SetValue(v string) {
	x.Value = v
}

func (x *SecurityInsightTrait) SetObservedAt(v *timestamppb.Timestamp) {
	x.ObservedAt = v
}

func (x *SecurityInsightTrait) SetContext(v *structpb.Struct) {
	x.Context = v
}

func (x *SecurityInsightTrait) SetUser(v *SecurityInsightTrait_UserTarget) {
	if v == nil {
		x.Target = nil
		return
	}
	x.Target = &SecurityInsightTrait_User{v}
}

func (x *SecurityInsightTrait) SetResource(v *SecurityInsightTrait_ResourceTarget) {
	if v == nil {
		x.Target = nil
		return
	}
	x.Target = &SecurityInsightTrait_Resource{v}
}

func (x *SecurityInsightTrait) HasObservedAt() bool {
	if x == nil {
		return false
	}
	return x.ObservedAt != nil
}

func (x *SecurityInsightTrait) HasContext() bool {
	if x == nil {
		return false
	}
	return x.Context != nil
}

func (x *SecurityInsightTrait) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.Target != nil
}

func (x *SecurityInsightTrait) HasUser() bool {
	if x == nil {
		return false
	}
	_, ok := x.Target.(*SecurityInsightTrait_User)
	return ok
}

func (x *SecurityInsightTrait) HasResource() bool {
	if x == nil {
		return false
	}
	_, ok := x.Target.(*SecurityInsightTrait_Resource)
	return ok
}

func (x *SecurityInsightTrait) ClearObservedAt() {
	x.ObservedAt = nil
}

func (x *SecurityInsightTrait) ClearContext() {
	x.Context = nil
}

func (x *SecurityInsightTrait) ClearTarget() {
	x.Target = nil
}

func (x *SecurityInsightTrait) ClearUser() {
	if _, ok := x.Target.(*SecurityInsightTrait_User); ok {
		x.Target = nil
	}
}

func (x *SecurityInsightTrait) ClearResource() {
	if _, ok := x.Target.(*SecurityInsightTrait_Resource); ok {
		x.Target = nil
	}
}

const SecurityInsightTrait_Target_not_set_case case_SecurityInsightTrait_Target = 0
const SecurityInsightTrait_User_case case_SecurityInsightTrait_Target = 5
const SecurityInsightTrait_Resource_case case_SecurityInsightTrait_Target = 6

func (x *SecurityInsightTrait) WhichTarget() case_SecurityInsightTrait_Target {
	if x == nil {
		return SecurityInsightTrait_Target_not_set_case
	}
	switch x.Target.(type) {
	case *SecurityInsightTrait_User:
		return SecurityInsightTrait_User_case
	case *SecurityInsightTrait_Resource:
		return SecurityInsightTrait_Resource_case
	default:
		return SecurityInsightTrait_Target_not_set_case
	}
}

type SecurityInsightTrait_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The type of insight (e.g., "crowdstrike_zta_score", "wiz_critical_vulnerability")
	InsightType string
	// The value of the insight (e.g., "85", "High", "Critical")
	Value string
	// When this insight was observed/captured from the source system
	ObservedAt *timestamppb.Timestamp
	// Additional structured context (deep links, remediation steps, etc.)
	Context *structpb.Struct
	// The target entity this insight should be bound to by Uplift

	// Fields of oneof Target:
	// For binding to a C1 User by email address
	User *SecurityInsightTrait_UserTarget
	// For binding to an AppResource by external ID
	Resource *SecurityInsightTrait_ResourceTarget
	// -- end of Target
}

func (b0 SecurityInsightTrait_builder) Build() *SecurityInsightTrait {
	m0 := &SecurityInsightTrait{}
	b, x := &b0, m0
	_, _ = b, x
	x.InsightType = b.InsightType
	x.Value = b.Value
	x.ObservedAt = b.ObservedAt
	x.Context = b.Context
	if b.User != nil {
		x.Target = &SecurityInsightTrait_User{b.User}
	}
	if b.Resource != nil {
		x.Target = &SecurityInsightTrait_Resource{b.Resource}
	}
	return m0
}

type case_SecurityInsightTrait_Target protoreflect.FieldNumber

func (x case_SecurityInsightTrait_Target) String() string {
	md := file_c1_connector_v2_annotation_security_insight_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSecurityInsightTrait_Target interface {
	isSecurityInsightTrait_Target()
}

type SecurityInsightTrait_User struct {
	// For binding to a C1 User by email address
	User *SecurityInsightTrait_UserTarget `protobuf:"bytes,5,opt,name=user,proto3,oneof"`
}

type SecurityInsightTrait_Resource struct {
	// For binding to an AppResource by external ID
	Resource *SecurityInsightTrait_ResourceTarget `protobuf:"bytes,6,opt,name=resource,proto3,oneof"`
}

func (*SecurityInsightTrait_User) isSecurityInsightTrait_Target() {}

func (*SecurityInsightTrait_Resource) isSecurityInsightTrait_Target() {}

// UserTarget identifies a user by email for resolution to a C1 User
type SecurityInsightTrait_UserTarget struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityInsightTrait_UserTarget) Reset() {
	*x = SecurityInsightTrait_UserTarget{}
	mi := &file_c1_connector_v2_annotation_security_insight_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityInsightTrait_UserTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityInsightTrait_UserTarget) ProtoMessage() {}

func (x *SecurityInsightTrait_UserTarget) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connector_v2_annotation_security_insight_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecurityInsightTrait_UserTarget) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SecurityInsightTrait_UserTarget) SetEmail(v string) {
	x.Email = v
}

type SecurityInsightTrait_UserTarget_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Email string
}

func (b0 SecurityInsightTrait_UserTarget_builder) Build() *SecurityInsightTrait_UserTarget {
	m0 := &SecurityInsightTrait_UserTarget{}
	b, x := &b0, m0
	_, _ = b, x
	x.Email = b.Email
	return m0
}

// ResourceTarget identifies a resource by external ID for resolution to an AppResource
type SecurityInsightTrait_ResourceTarget struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The external identifier of the resource (e.g., ARN, GUID, etc.)
	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// Optional hint to help find the owning app (e.g., "aws", "github")
	AppHint       string `protobuf:"bytes,2,opt,name=app_hint,json=appHint,proto3" json:"app_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityInsightTrait_ResourceTarget) Reset() {
	*x = SecurityInsightTrait_ResourceTarget{}
	mi := &file_c1_connector_v2_annotation_security_insight_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityInsightTrait_ResourceTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityInsightTrait_ResourceTarget) ProtoMessage() {}

func (x *SecurityInsightTrait_ResourceTarget) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connector_v2_annotation_security_insight_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecurityInsightTrait_ResourceTarget) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *SecurityInsightTrait_ResourceTarget) GetAppHint() string {
	if x != nil {
		return x.AppHint
	}
	return ""
}

func (x *SecurityInsightTrait_ResourceTarget) SetExternalId(v string) {
	x.ExternalId = v
}

func (x *SecurityInsightTrait_ResourceTarget) SetAppHint(v string) {
	x.AppHint = v
}

type SecurityInsightTrait_ResourceTarget_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The external identifier of the resource (e.g., ARN, GUID, etc.)
	ExternalId string
	// Optional hint to help find the owning app (e.g., "aws", "github")
	AppHint string
}

func (b0 SecurityInsightTrait_ResourceTarget_builder) Build() *SecurityInsightTrait_ResourceTarget {
	m0 := &SecurityInsightTrait_ResourceTarget{}
	b, x := &b0, m0
	_, _ = b, x
	x.ExternalId = b.ExternalId
	x.AppHint = b.AppHint
	return m0
}

var File_c1_connector_v2_annotation_security_insight_proto protoreflect.FileDescriptor

const file_c1_connector_v2_annotation_security_insight_proto_rawDesc = "" +
	"\n" +
	"1c1/connector/v2/annotation_security_insight.proto\x12\x0fc1.connector.v2\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\x96\x04\n" +
	"\x14SecurityInsightTrait\x12-\n" +
	"\finsight_type\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05 \x01(\x80\bR\vinsightType\x12 \n" +
	"\x05value\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05 \x01(\x80\bR\x05value\x12;\n" +
	"\vobserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x121\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructR\acontext\x12F\n" +
	"\x04user\x18\x05 \x01(\v20.c1.connector.v2.SecurityInsightTrait.UserTargetH\x00R\x04user\x12R\n" +
	"\bresource\x18\x06 \x01(\v24.c1.connector.v2.SecurityInsightTrait.ResourceTargetH\x00R\bresource\x1a0\n" +
	"\n" +
	"UserTarget\x12\"\n" +
	"\x05email\x18\x01 \x01(\tB\f\xfaB\tr\a \x01(\x80\b`\x01R\x05email\x1ae\n" +
	"\x0eResourceTarget\x12+\n" +
	"\vexternal_id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05 \x01(\x80 R\n" +
	"externalId\x12&\n" +
	"\bapp_hint\x18\x02 \x01(\tB\v\xfaB\br\x06(\x80\b\xd0\x01\x01R\aappHintB\b\n" +
	"\x06targetB6Z4github.com/conductorone/baton-sdk/pb/c1/connector/v2b\x06proto3"

var file_c1_connector_v2_annotation_security_insight_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_c1_connector_v2_annotation_security_insight_proto_goTypes = []any{
	(*SecurityInsightTrait)(nil),                // 0: c1.connector.v2.SecurityInsightTrait
	(*SecurityInsightTrait_UserTarget)(nil),     // 1: c1.connector.v2.SecurityInsightTrait.UserTarget
	(*SecurityInsightTrait_ResourceTarget)(nil), // 2: c1.connector.v2.SecurityInsightTrait.ResourceTarget
	(*timestamppb.Timestamp)(nil),               // 3: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                     // 4: google.protobuf.Struct
}
var file_c1_connector_v2_annotation_security_insight_proto_depIdxs = []int32{
	3, // 0: c1.connector.v2.SecurityInsightTrait.observed_at:type_name -> google.protobuf.Timestamp
	4, // 1: c1.connector.v2.SecurityInsightTrait.context:type_name -> google.protobuf.Struct
	1, // 2: c1.connector.v2.SecurityInsightTrait.user:type_name -> c1.connector.v2.SecurityInsightTrait.UserTarget
	2, // 3: c1.connector.v2.SecurityInsightTrait.resource:type_name -> c1.connector.v2.SecurityInsightTrait.ResourceTarget
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_c1_connector_v2_annotation_security_insight_proto_init() }
func file_c1_connector_v2_annotation_security_insight_proto_init() {
	if File_c1_connector_v2_annotation_security_insight_proto != nil {
		return
	}
	file_c1_connector_v2_annotation_security_insight_proto_msgTypes[0].OneofWrappers = []any{
		(*SecurityInsightTrait_User)(nil),
		(*SecurityInsightTrait_Resource)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c1_connector_v2_annotation_security_insight_proto_rawDesc), len(file_c1_connector_v2_annotation_security_insight_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c1_connector_v2_annotation_security_insight_proto_goTypes,
		DependencyIndexes: file_c1_connector_v2_annotation_security_insight_proto_depIdxs,
		MessageInfos:      file_c1_connector_v2_annotation_security_insight_proto_msgTypes,
	}.Build()
	File_c1_connector_v2_annotation_security_insight_proto = out.File
	file_c1_connector_v2_annotation_security_insight_proto_goTypes = nil
	file_c1_connector_v2_annotation_security_insight_proto_depIdxs = nil
}
