// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: c1/connector/v2/annotation_session.proto

package v2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SessionStoreUsage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SessionStoreUsage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SessionStoreUsage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SessionStoreUsageMultiError, or nil if none found.
func (m *SessionStoreUsage) ValidateAll() error {
	return m.validate(true)
}

func (m *SessionStoreUsage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Kind

	for idx, item := range m.GetOps() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SessionStoreUsageValidationError{
						field:  fmt.Sprintf("Ops[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SessionStoreUsageValidationError{
						field:  fmt.Sprintf("Ops[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SessionStoreUsageValidationError{
					field:  fmt.Sprintf("Ops[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SessionStoreUsageMultiError(errors)
	}

	return nil
}

// SessionStoreUsageMultiError is an error wrapping multiple validation errors
// returned by SessionStoreUsage.ValidateAll() if the designated constraints
// aren't met.
type SessionStoreUsageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SessionStoreUsageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SessionStoreUsageMultiError) AllErrors() []error { return m }

// SessionStoreUsageValidationError is the validation error returned by
// SessionStoreUsage.Validate if the designated constraints aren't met.
type SessionStoreUsageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SessionStoreUsageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SessionStoreUsageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SessionStoreUsageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SessionStoreUsageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SessionStoreUsageValidationError) ErrorName() string {
	return "SessionStoreUsageValidationError"
}

// Error satisfies the builtin error interface
func (e SessionStoreUsageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSessionStoreUsage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SessionStoreUsageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SessionStoreUsageValidationError{}

// Validate checks the field values on SessionStoreUsage_OpStats with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SessionStoreUsage_OpStats) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SessionStoreUsage_OpStats with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SessionStoreUsage_OpStatsMultiError, or nil if none found.
func (m *SessionStoreUsage_OpStats) ValidateAll() error {
	return m.validate(true)
}

func (m *SessionStoreUsage_OpStats) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Op

	// no validation rules for Count

	// no validation rules for Errors

	// no validation rules for Timeouts

	// no validation rules for TotalMs

	// no validation rules for MaxMs

	if len(errors) > 0 {
		return SessionStoreUsage_OpStatsMultiError(errors)
	}

	return nil
}

// SessionStoreUsage_OpStatsMultiError is an error wrapping multiple validation
// errors returned by SessionStoreUsage_OpStats.ValidateAll() if the
// designated constraints aren't met.
type SessionStoreUsage_OpStatsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SessionStoreUsage_OpStatsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SessionStoreUsage_OpStatsMultiError) AllErrors() []error { return m }

// SessionStoreUsage_OpStatsValidationError is the validation error returned by
// SessionStoreUsage_OpStats.Validate if the designated constraints aren't met.
type SessionStoreUsage_OpStatsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SessionStoreUsage_OpStatsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SessionStoreUsage_OpStatsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SessionStoreUsage_OpStatsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SessionStoreUsage_OpStatsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SessionStoreUsage_OpStatsValidationError) ErrorName() string {
	return "SessionStoreUsage_OpStatsValidationError"
}

// Error satisfies the builtin error interface
func (e SessionStoreUsage_OpStatsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSessionStoreUsage_OpStats.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SessionStoreUsage_OpStatsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SessionStoreUsage_OpStatsValidationError{}
