// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: c1/connector/v2/annotation_grants_revoked.proto

//go:build !protoopaque

package v2

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GrantsRevoked is attached by a connector to a Revoke response when the
// operation removed additional grants for the same principal.
type GrantsRevoked struct {
	state          protoimpl.MessageState `protogen:"hybrid.v1"`
	EntitlementIds []string               `protobuf:"bytes,1,rep,name=entitlement_ids,json=entitlementIds,proto3" json:"entitlement_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GrantsRevoked) Reset() {
	*x = GrantsRevoked{}
	mi := &file_c1_connector_v2_annotation_grants_revoked_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantsRevoked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantsRevoked) ProtoMessage() {}

func (x *GrantsRevoked) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connector_v2_annotation_grants_revoked_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GrantsRevoked) GetEntitlementIds() []string {
	if x != nil {
		return x.EntitlementIds
	}
	return nil
}

func (x *GrantsRevoked) SetEntitlementIds(v []string) {
	x.EntitlementIds = v
}

type GrantsRevoked_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EntitlementIds []string
}

func (b0 GrantsRevoked_builder) Build() *GrantsRevoked {
	m0 := &GrantsRevoked{}
	b, x := &b0, m0
	_, _ = b, x
	x.EntitlementIds = b.EntitlementIds
	return m0
}

var File_c1_connector_v2_annotation_grants_revoked_proto protoreflect.FileDescriptor

const file_c1_connector_v2_annotation_grants_revoked_proto_rawDesc = "" +
	"\n" +
	"/c1/connector/v2/annotation_grants_revoked.proto\x12\x0fc1.connector.v2\x1a\x17validate/validate.proto\"F\n" +
	"\rGrantsRevoked\x125\n" +
	"\x0fentitlement_ids\x18\x01 \x03(\tB\f\xfaB\t\x92\x01\x06\"\x04r\x02 \x01R\x0eentitlementIdsB6Z4github.com/conductorone/baton-sdk/pb/c1/connector/v2b\x06proto3"

var file_c1_connector_v2_annotation_grants_revoked_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_c1_connector_v2_annotation_grants_revoked_proto_goTypes = []any{
	(*GrantsRevoked)(nil), // 0: c1.connector.v2.GrantsRevoked
}
var file_c1_connector_v2_annotation_grants_revoked_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_c1_connector_v2_annotation_grants_revoked_proto_init() }
func file_c1_connector_v2_annotation_grants_revoked_proto_init() {
	if File_c1_connector_v2_annotation_grants_revoked_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c1_connector_v2_annotation_grants_revoked_proto_rawDesc), len(file_c1_connector_v2_annotation_grants_revoked_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c1_connector_v2_annotation_grants_revoked_proto_goTypes,
		DependencyIndexes: file_c1_connector_v2_annotation_grants_revoked_proto_depIdxs,
		MessageInfos:      file_c1_connector_v2_annotation_grants_revoked_proto_msgTypes,
	}.Build()
	File_c1_connector_v2_annotation_grants_revoked_proto = out.File
	file_c1_connector_v2_annotation_grants_revoked_proto_goTypes = nil
	file_c1_connector_v2_annotation_grants_revoked_proto_depIdxs = nil
}
