// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: baton/v1/outputs.proto

//go:build protoopaque

package v1

import (
	v2 "github.com/conductorone/baton-sdk/pb/c1/connector/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceDiff struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Created  *[]*v2.Resource        `protobuf:"bytes,1,rep,name=created,proto3"`
	xxx_hidden_Deleted  *[]*v2.Resource        `protobuf:"bytes,2,rep,name=deleted,proto3"`
	xxx_hidden_Modified *[]*v2.Resource        `protobuf:"bytes,3,rep,name=modified,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResourceDiff) Reset() {
	*x = ResourceDiff{}
	mi := &file_baton_v1_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDiff) ProtoMessage() {}

func (x *ResourceDiff) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceDiff) GetCreated() []*v2.Resource {
	if x != nil {
		if x.xxx_hidden_Created != nil {
			return *x.xxx_hidden_Created
		}
	}
	return nil
}

func (x *ResourceDiff) GetDeleted() []*v2.Resource {
	if x != nil {
		if x.xxx_hidden_Deleted != nil {
			return *x.xxx_hidden_Deleted
		}
	}
	return nil
}

func (x *ResourceDiff) GetModified() []*v2.Resource {
	if x != nil {
		if x.xxx_hidden_Modified != nil {
			return *x.xxx_hidden_Modified
		}
	}
	return nil
}

func (x *ResourceDiff) SetCreated(v []*v2.Resource) {
	x.xxx_hidden_Created = &v
}

func (x *ResourceDiff) SetDeleted(v []*v2.Resource) {
	x.xxx_hidden_Deleted = &v
}

func (x *ResourceDiff) SetModified(v []*v2.Resource) {
	x.xxx_hidden_Modified = &v
}

type ResourceDiff_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Created  []*v2.Resource
	Deleted  []*v2.Resource
	Modified []*v2.Resource
}

func (b0 ResourceDiff_builder) Build() *ResourceDiff {
	m0 := &ResourceDiff{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Created = &b.Created
	x.xxx_hidden_Deleted = &b.Deleted
	x.xxx_hidden_Modified = &b.Modified
	return m0
}

type EntitlementDiff struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Created  *[]*v2.Entitlement     `protobuf:"bytes,1,rep,name=created,proto3"`
	xxx_hidden_Deleted  *[]*v2.Entitlement     `protobuf:"bytes,2,rep,name=deleted,proto3"`
	xxx_hidden_Modified *[]*v2.Entitlement     `protobuf:"bytes,3,rep,name=modified,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EntitlementDiff) Reset() {
	*x = EntitlementDiff{}
	mi := &file_baton_v1_outputs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitlementDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitlementDiff) ProtoMessage() {}

func (x *EntitlementDiff) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EntitlementDiff) GetCreated() []*v2.Entitlement {
	if x != nil {
		if x.xxx_hidden_Created != nil {
			return *x.xxx_hidden_Created
		}
	}
	return nil
}

func (x *EntitlementDiff) GetDeleted() []*v2.Entitlement {
	if x != nil {
		if x.xxx_hidden_Deleted != nil {
			return *x.xxx_hidden_Deleted
		}
	}
	return nil
}

func (x *EntitlementDiff) GetModified() []*v2.Entitlement {
	if x != nil {
		if x.xxx_hidden_Modified != nil {
			return *x.xxx_hidden_Modified
		}
	}
	return nil
}

func (x *EntitlementDiff) SetCreated(v []*v2.Entitlement) {
	x.xxx_hidden_Created = &v
}

func (x *EntitlementDiff) SetDeleted(v []*v2.Entitlement) {
	x.xxx_hidden_Deleted = &v
}

func (x *EntitlementDiff) SetModified(v []*v2.Entitlement) {
	x.xxx_hidden_Modified = &v
}

type EntitlementDiff_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Created  []*v2.Entitlement
	Deleted  []*v2.Entitlement
	Modified []*v2.Entitlement
}

func (b0 EntitlementDiff_builder) Build() *EntitlementDiff {
	m0 := &EntitlementDiff{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Created = &b.Created
	x.xxx_hidden_Deleted = &b.Deleted
	x.xxx_hidden_Modified = &b.Modified
	return m0
}

type GrantDiff struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Created  *[]*v2.Grant           `protobuf:"bytes,1,rep,name=created,proto3"`
	xxx_hidden_Deleted  *[]*v2.Grant           `protobuf:"bytes,2,rep,name=deleted,proto3"`
	xxx_hidden_Modified *[]*v2.Grant           `protobuf:"bytes,3,rep,name=modified,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GrantDiff) Reset() {
	*x = GrantDiff{}
	mi := &file_baton_v1_outputs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantDiff) ProtoMessage() {}

func (x *GrantDiff) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GrantDiff) GetCreated() []*v2.Grant {
	if x != nil {
		if x.xxx_hidden_Created != nil {
			return *x.xxx_hidden_Created
		}
	}
	return nil
}

func (x *GrantDiff) GetDeleted() []*v2.Grant {
	if x != nil {
		if x.xxx_hidden_Deleted != nil {
			return *x.xxx_hidden_Deleted
		}
	}
	return nil
}

func (x *GrantDiff) GetModified() []*v2.Grant {
	if x != nil {
		if x.xxx_hidden_Modified != nil {
			return *x.xxx_hidden_Modified
		}
	}
	return nil
}

func (x *GrantDiff) SetCreated(v []*v2.Grant) {
	x.xxx_hidden_Created = &v
}

func (x *GrantDiff) SetDeleted(v []*v2.Grant) {
	x.xxx_hidden_Deleted = &v
}

func (x *GrantDiff) SetModified(v []*v2.Grant) {
	x.xxx_hidden_Modified = &v
}

type GrantDiff_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Created  []*v2.Grant
	Deleted  []*v2.Grant
	Modified []*v2.Grant
}

func (b0 GrantDiff_builder) Build() *GrantDiff {
	m0 := &GrantDiff{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Created = &b.Created
	x.xxx_hidden_Deleted = &b.Deleted
	x.xxx_hidden_Modified = &b.Modified
	return m0
}

type C1ZDiffOutput struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Resources    *ResourceDiff          `protobuf:"bytes,1,opt,name=resources,proto3"`
	xxx_hidden_Entitlements *EntitlementDiff       `protobuf:"bytes,2,opt,name=entitlements,proto3"`
	xxx_hidden_Grants       *GrantDiff             `protobuf:"bytes,3,opt,name=grants,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *C1ZDiffOutput) Reset() {
	*x = C1ZDiffOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C1ZDiffOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C1ZDiffOutput) ProtoMessage() {}

func (x *C1ZDiffOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *C1ZDiffOutput) GetResources() *ResourceDiff {
	if x != nil {
		return x.xxx_hidden_Resources
	}
	return nil
}

func (x *C1ZDiffOutput) GetEntitlements() *EntitlementDiff {
	if x != nil {
		return x.xxx_hidden_Entitlements
	}
	return nil
}

func (x *C1ZDiffOutput) GetGrants() *GrantDiff {
	if x != nil {
		return x.xxx_hidden_Grants
	}
	return nil
}

func (x *C1ZDiffOutput) SetResources(v *ResourceDiff) {
	x.xxx_hidden_Resources = v
}

func (x *C1ZDiffOutput) SetEntitlements(v *EntitlementDiff) {
	x.xxx_hidden_Entitlements = v
}

func (x *C1ZDiffOutput) SetGrants(v *GrantDiff) {
	x.xxx_hidden_Grants = v
}

func (x *C1ZDiffOutput) HasResources() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Resources != nil
}

func (x *C1ZDiffOutput) HasEntitlements() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Entitlements != nil
}

func (x *C1ZDiffOutput) HasGrants() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Grants != nil
}

func (x *C1ZDiffOutput) ClearResources() {
	x.xxx_hidden_Resources = nil
}

func (x *C1ZDiffOutput) ClearEntitlements() {
	x.xxx_hidden_Entitlements = nil
}

func (x *C1ZDiffOutput) ClearGrants() {
	x.xxx_hidden_Grants = nil
}

type C1ZDiffOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Resources    *ResourceDiff
	Entitlements *EntitlementDiff
	Grants       *GrantDiff
}

func (b0 C1ZDiffOutput_builder) Build() *C1ZDiffOutput {
	m0 := &C1ZDiffOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Resources = b.Resources
	x.xxx_hidden_Entitlements = b.Entitlements
	x.xxx_hidden_Grants = b.Grants
	return m0
}

type ResourceTypeOutput struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResourceType *v2.ResourceType       `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResourceTypeOutput) Reset() {
	*x = ResourceTypeOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceTypeOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTypeOutput) ProtoMessage() {}

func (x *ResourceTypeOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceTypeOutput) GetResourceType() *v2.ResourceType {
	if x != nil {
		return x.xxx_hidden_ResourceType
	}
	return nil
}

func (x *ResourceTypeOutput) SetResourceType(v *v2.ResourceType) {
	x.xxx_hidden_ResourceType = v
}

func (x *ResourceTypeOutput) HasResourceType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ResourceType != nil
}

func (x *ResourceTypeOutput) ClearResourceType() {
	x.xxx_hidden_ResourceType = nil
}

type ResourceTypeOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResourceType *v2.ResourceType
}

func (b0 ResourceTypeOutput_builder) Build() *ResourceTypeOutput {
	m0 := &ResourceTypeOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResourceType = b.ResourceType
	return m0
}

type ResourceOutput struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Resource     *v2.Resource           `protobuf:"bytes,1,opt,name=resource,proto3"`
	xxx_hidden_ResourceType *v2.ResourceType       `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3"`
	xxx_hidden_Parent       *v2.Resource           `protobuf:"bytes,3,opt,name=parent,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResourceOutput) Reset() {
	*x = ResourceOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceOutput) ProtoMessage() {}

func (x *ResourceOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceOutput) GetResource() *v2.Resource {
	if x != nil {
		return x.xxx_hidden_Resource
	}
	return nil
}

func (x *ResourceOutput) GetResourceType() *v2.ResourceType {
	if x != nil {
		return x.xxx_hidden_ResourceType
	}
	return nil
}

func (x *ResourceOutput) GetParent() *v2.Resource {
	if x != nil {
		return x.xxx_hidden_Parent
	}
	return nil
}

func (x *ResourceOutput) SetResource(v *v2.Resource) {
	x.xxx_hidden_Resource = v
}

func (x *ResourceOutput) SetResourceType(v *v2.ResourceType) {
	x.xxx_hidden_ResourceType = v
}

func (x *ResourceOutput) SetParent(v *v2.Resource) {
	x.xxx_hidden_Parent = v
}

func (x *ResourceOutput) HasResource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Resource != nil
}

func (x *ResourceOutput) HasResourceType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ResourceType != nil
}

func (x *ResourceOutput) HasParent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Parent != nil
}

func (x *ResourceOutput) ClearResource() {
	x.xxx_hidden_Resource = nil
}

func (x *ResourceOutput) ClearResourceType() {
	x.xxx_hidden_ResourceType = nil
}

func (x *ResourceOutput) ClearParent() {
	x.xxx_hidden_Parent = nil
}

type ResourceOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Resource     *v2.Resource
	ResourceType *v2.ResourceType
	Parent       *v2.Resource
}

func (b0 ResourceOutput_builder) Build() *ResourceOutput {
	m0 := &ResourceOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Resource = b.Resource
	x.xxx_hidden_ResourceType = b.ResourceType
	x.xxx_hidden_Parent = b.Parent
	return m0
}

type EntitlementOutput struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entitlement  *v2.Entitlement        `protobuf:"bytes,1,opt,name=entitlement,proto3"`
	xxx_hidden_Resource     *v2.Resource           `protobuf:"bytes,2,opt,name=resource,proto3"`
	xxx_hidden_ResourceType *v2.ResourceType       `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *EntitlementOutput) Reset() {
	*x = EntitlementOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitlementOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitlementOutput) ProtoMessage() {}

func (x *EntitlementOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EntitlementOutput) GetEntitlement() *v2.Entitlement {
	if x != nil {
		return x.xxx_hidden_Entitlement
	}
	return nil
}

func (x *EntitlementOutput) GetResource() *v2.Resource {
	if x != nil {
		return x.xxx_hidden_Resource
	}
	return nil
}

func (x *EntitlementOutput) GetResourceType() *v2.ResourceType {
	if x != nil {
		return x.xxx_hidden_ResourceType
	}
	return nil
}

func (x *EntitlementOutput) SetEntitlement(v *v2.Entitlement) {
	x.xxx_hidden_Entitlement = v
}

func (x *EntitlementOutput) SetResource(v *v2.Resource) {
	x.xxx_hidden_Resource = v
}

func (x *EntitlementOutput) SetResourceType(v *v2.ResourceType) {
	x.xxx_hidden_ResourceType = v
}

func (x *EntitlementOutput) HasEntitlement() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Entitlement != nil
}

func (x *EntitlementOutput) HasResource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Resource != nil
}

func (x *EntitlementOutput) HasResourceType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ResourceType != nil
}

func (x *EntitlementOutput) ClearEntitlement() {
	x.xxx_hidden_Entitlement = nil
}

func (x *EntitlementOutput) ClearResource() {
	x.xxx_hidden_Resource = nil
}

func (x *EntitlementOutput) ClearResourceType() {
	x.xxx_hidden_ResourceType = nil
}

type EntitlementOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entitlement  *v2.Entitlement
	Resource     *v2.Resource
	ResourceType *v2.ResourceType
}

func (b0 EntitlementOutput_builder) Build() *EntitlementOutput {
	m0 := &EntitlementOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entitlement = b.Entitlement
	x.xxx_hidden_Resource = b.Resource
	x.xxx_hidden_ResourceType = b.ResourceType
	return m0
}

type GrantOutput struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Grant        *v2.Grant              `protobuf:"bytes,1,opt,name=grant,proto3"`
	xxx_hidden_Entitlement  *v2.Entitlement        `protobuf:"bytes,2,opt,name=entitlement,proto3"`
	xxx_hidden_Resource     *v2.Resource           `protobuf:"bytes,3,opt,name=resource,proto3"`
	xxx_hidden_ResourceType *v2.ResourceType       `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3"`
	xxx_hidden_Principal    *v2.Resource           `protobuf:"bytes,5,opt,name=principal,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GrantOutput) Reset() {
	*x = GrantOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantOutput) ProtoMessage() {}

func (x *GrantOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GrantOutput) GetGrant() *v2.Grant {
	if x != nil {
		return x.xxx_hidden_Grant
	}
	return nil
}

func (x *GrantOutput) GetEntitlement() *v2.Entitlement {
	if x != nil {
		return x.xxx_hidden_Entitlement
	}
	return nil
}

func (x *GrantOutput) GetResource() *v2.Resource {
	if x != nil {
		return x.xxx_hidden_Resource
	}
	return nil
}

func (x *GrantOutput) GetResourceType() *v2.ResourceType {
	if x != nil {
		return x.xxx_hidden_ResourceType
	}
	return nil
}

func (x *GrantOutput) GetPrincipal() *v2.Resource {
	if x != nil {
		return x.xxx_hidden_Principal
	}
	return nil
}

func (x *GrantOutput) SetGrant(v *v2.Grant) {
	x.xxx_hidden_Grant = v
}

func (x *GrantOutput) SetEntitlement(v *v2.Entitlement) {
	x.xxx_hidden_Entitlement = v
}

func (x *GrantOutput) SetResource(v *v2.Resource) {
	x.xxx_hidden_Resource = v
}

func (x *GrantOutput) SetResourceType(v *v2.ResourceType) {
	x.xxx_hidden_ResourceType = v
}

func (x *GrantOutput) SetPrincipal(v *v2.Resource) {
	x.xxx_hidden_Principal = v
}

func (x *GrantOutput) HasGrant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Grant != nil
}

func (x *GrantOutput) HasEntitlement() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Entitlement != nil
}

func (x *GrantOutput) HasResource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Resource != nil
}

func (x *GrantOutput) HasResourceType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ResourceType != nil
}

func (x *GrantOutput) HasPrincipal() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Principal != nil
}

func (x *GrantOutput) ClearGrant() {
	x.xxx_hidden_Grant = nil
}

func (x *GrantOutput) ClearEntitlement() {
	x.xxx_hidden_Entitlement = nil
}

func (x *GrantOutput) ClearResource() {
	x.xxx_hidden_Resource = nil
}

func (x *GrantOutput) ClearResourceType() {
	x.xxx_hidden_ResourceType = nil
}

func (x *GrantOutput) ClearPrincipal() {
	x.xxx_hidden_Principal = nil
}

type GrantOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Grant        *v2.Grant
	Entitlement  *v2.Entitlement
	Resource     *v2.Resource
	ResourceType *v2.ResourceType
	Principal    *v2.Resource
}

func (b0 GrantOutput_builder) Build() *GrantOutput {
	m0 := &GrantOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Grant = b.Grant
	x.xxx_hidden_Entitlement = b.Entitlement
	x.xxx_hidden_Resource = b.Resource
	x.xxx_hidden_ResourceType = b.ResourceType
	x.xxx_hidden_Principal = b.Principal
	return m0
}

type ResourceAccessOutput struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResourceType *v2.ResourceType       `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3"`
	xxx_hidden_Resource     *v2.Resource           `protobuf:"bytes,2,opt,name=resource,proto3"`
	xxx_hidden_Entitlements *[]*v2.Entitlement     `protobuf:"bytes,3,rep,name=entitlements,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResourceAccessOutput) Reset() {
	*x = ResourceAccessOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAccessOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAccessOutput) ProtoMessage() {}

func (x *ResourceAccessOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceAccessOutput) GetResourceType() *v2.ResourceType {
	if x != nil {
		return x.xxx_hidden_ResourceType
	}
	return nil
}

func (x *ResourceAccessOutput) GetResource() *v2.Resource {
	if x != nil {
		return x.xxx_hidden_Resource
	}
	return nil
}

func (x *ResourceAccessOutput) GetEntitlements() []*v2.Entitlement {
	if x != nil {
		if x.xxx_hidden_Entitlements != nil {
			return *x.xxx_hidden_Entitlements
		}
	}
	return nil
}

func (x *ResourceAccessOutput) SetResourceType(v *v2.ResourceType) {
	x.xxx_hidden_ResourceType = v
}

func (x *ResourceAccessOutput) SetResource(v *v2.Resource) {
	x.xxx_hidden_Resource = v
}

func (x *ResourceAccessOutput) SetEntitlements(v []*v2.Entitlement) {
	x.xxx_hidden_Entitlements = &v
}

func (x *ResourceAccessOutput) HasResourceType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ResourceType != nil
}

func (x *ResourceAccessOutput) HasResource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Resource != nil
}

func (x *ResourceAccessOutput) ClearResourceType() {
	x.xxx_hidden_ResourceType = nil
}

func (x *ResourceAccessOutput) ClearResource() {
	x.xxx_hidden_Resource = nil
}

type ResourceAccessOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResourceType *v2.ResourceType
	Resource     *v2.Resource
	Entitlements []*v2.Entitlement
}

func (b0 ResourceAccessOutput_builder) Build() *ResourceAccessOutput {
	m0 := &ResourceAccessOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResourceType = b.ResourceType
	x.xxx_hidden_Resource = b.Resource
	x.xxx_hidden_Entitlements = &b.Entitlements
	return m0
}

type ResourceTypeListOutput struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResourceTypes *[]*ResourceTypeOutput `protobuf:"bytes,1,rep,name=resource_types,json=resourceTypes,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ResourceTypeListOutput) Reset() {
	*x = ResourceTypeListOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceTypeListOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTypeListOutput) ProtoMessage() {}

func (x *ResourceTypeListOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceTypeListOutput) GetResourceTypes() []*ResourceTypeOutput {
	if x != nil {
		if x.xxx_hidden_ResourceTypes != nil {
			return *x.xxx_hidden_ResourceTypes
		}
	}
	return nil
}

func (x *ResourceTypeListOutput) SetResourceTypes(v []*ResourceTypeOutput) {
	x.xxx_hidden_ResourceTypes = &v
}

type ResourceTypeListOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResourceTypes []*ResourceTypeOutput
}

func (b0 ResourceTypeListOutput_builder) Build() *ResourceTypeListOutput {
	m0 := &ResourceTypeListOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResourceTypes = &b.ResourceTypes
	return m0
}

type ResourceListOutput struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Resources *[]*ResourceOutput     `protobuf:"bytes,1,rep,name=resources,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceListOutput) Reset() {
	*x = ResourceListOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceListOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceListOutput) ProtoMessage() {}

func (x *ResourceListOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceListOutput) GetResources() []*ResourceOutput {
	if x != nil {
		if x.xxx_hidden_Resources != nil {
			return *x.xxx_hidden_Resources
		}
	}
	return nil
}

func (x *ResourceListOutput) SetResources(v []*ResourceOutput) {
	x.xxx_hidden_Resources = &v
}

type ResourceListOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Resources []*ResourceOutput
}

func (b0 ResourceListOutput_builder) Build() *ResourceListOutput {
	m0 := &ResourceListOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Resources = &b.Resources
	return m0
}

type EntitlementListOutput struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entitlements *[]*EntitlementOutput  `protobuf:"bytes,1,rep,name=entitlements,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *EntitlementListOutput) Reset() {
	*x = EntitlementListOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitlementListOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitlementListOutput) ProtoMessage() {}

func (x *EntitlementListOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EntitlementListOutput) GetEntitlements() []*EntitlementOutput {
	if x != nil {
		if x.xxx_hidden_Entitlements != nil {
			return *x.xxx_hidden_Entitlements
		}
	}
	return nil
}

func (x *EntitlementListOutput) SetEntitlements(v []*EntitlementOutput) {
	x.xxx_hidden_Entitlements = &v
}

type EntitlementListOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entitlements []*EntitlementOutput
}

func (b0 EntitlementListOutput_builder) Build() *EntitlementListOutput {
	m0 := &EntitlementListOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entitlements = &b.Entitlements
	return m0
}

type GrantListOutput struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Grants *[]*GrantOutput        `protobuf:"bytes,1,rep,name=grants,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GrantListOutput) Reset() {
	*x = GrantListOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantListOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantListOutput) ProtoMessage() {}

func (x *GrantListOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GrantListOutput) GetGrants() []*GrantOutput {
	if x != nil {
		if x.xxx_hidden_Grants != nil {
			return *x.xxx_hidden_Grants
		}
	}
	return nil
}

func (x *GrantListOutput) SetGrants(v []*GrantOutput) {
	x.xxx_hidden_Grants = &v
}

type GrantListOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Grants []*GrantOutput
}

func (b0 GrantListOutput_builder) Build() *GrantListOutput {
	m0 := &GrantListOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Grants = &b.Grants
	return m0
}

type ResourceAccessListOutput struct {
	state                protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Principal *v2.Resource             `protobuf:"bytes,1,opt,name=principal,proto3"`
	xxx_hidden_Access    *[]*ResourceAccessOutput `protobuf:"bytes,2,rep,name=access,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceAccessListOutput) Reset() {
	*x = ResourceAccessListOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAccessListOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAccessListOutput) ProtoMessage() {}

func (x *ResourceAccessListOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceAccessListOutput) GetPrincipal() *v2.Resource {
	if x != nil {
		return x.xxx_hidden_Principal
	}
	return nil
}

func (x *ResourceAccessListOutput) GetAccess() []*ResourceAccessOutput {
	if x != nil {
		if x.xxx_hidden_Access != nil {
			return *x.xxx_hidden_Access
		}
	}
	return nil
}

func (x *ResourceAccessListOutput) SetPrincipal(v *v2.Resource) {
	x.xxx_hidden_Principal = v
}

func (x *ResourceAccessListOutput) SetAccess(v []*ResourceAccessOutput) {
	x.xxx_hidden_Access = &v
}

func (x *ResourceAccessListOutput) HasPrincipal() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Principal != nil
}

func (x *ResourceAccessListOutput) ClearPrincipal() {
	x.xxx_hidden_Principal = nil
}

type ResourceAccessListOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Principal *v2.Resource
	Access    []*ResourceAccessOutput
}

func (b0 ResourceAccessListOutput_builder) Build() *ResourceAccessListOutput {
	m0 := &ResourceAccessListOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Principal = b.Principal
	x.xxx_hidden_Access = &b.Access
	return m0
}

type PrincipalsCompareOutput struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Missing  *[]*ResourceOutput     `protobuf:"bytes,1,rep,name=missing,proto3"`
	xxx_hidden_Extra    *[]*ResourceOutput     `protobuf:"bytes,2,rep,name=extra,proto3"`
	xxx_hidden_Base     *[]*ResourceOutput     `protobuf:"bytes,3,rep,name=base,proto3"`
	xxx_hidden_Compared *[]*ResourceOutput     `protobuf:"bytes,4,rep,name=compared,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PrincipalsCompareOutput) Reset() {
	*x = PrincipalsCompareOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrincipalsCompareOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalsCompareOutput) ProtoMessage() {}

func (x *PrincipalsCompareOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrincipalsCompareOutput) GetMissing() []*ResourceOutput {
	if x != nil {
		if x.xxx_hidden_Missing != nil {
			return *x.xxx_hidden_Missing
		}
	}
	return nil
}

func (x *PrincipalsCompareOutput) GetExtra() []*ResourceOutput {
	if x != nil {
		if x.xxx_hidden_Extra != nil {
			return *x.xxx_hidden_Extra
		}
	}
	return nil
}

func (x *PrincipalsCompareOutput) GetBase() []*ResourceOutput {
	if x != nil {
		if x.xxx_hidden_Base != nil {
			return *x.xxx_hidden_Base
		}
	}
	return nil
}

func (x *PrincipalsCompareOutput) GetCompared() []*ResourceOutput {
	if x != nil {
		if x.xxx_hidden_Compared != nil {
			return *x.xxx_hidden_Compared
		}
	}
	return nil
}

func (x *PrincipalsCompareOutput) SetMissing(v []*ResourceOutput) {
	x.xxx_hidden_Missing = &v
}

func (x *PrincipalsCompareOutput) SetExtra(v []*ResourceOutput) {
	x.xxx_hidden_Extra = &v
}

func (x *PrincipalsCompareOutput) SetBase(v []*ResourceOutput) {
	x.xxx_hidden_Base = &v
}

func (x *PrincipalsCompareOutput) SetCompared(v []*ResourceOutput) {
	x.xxx_hidden_Compared = &v
}

type PrincipalsCompareOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Missing  []*ResourceOutput
	Extra    []*ResourceOutput
	Base     []*ResourceOutput
	Compared []*ResourceOutput
}

func (b0 PrincipalsCompareOutput_builder) Build() *PrincipalsCompareOutput {
	m0 := &PrincipalsCompareOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Missing = &b.Missing
	x.xxx_hidden_Extra = &b.Extra
	x.xxx_hidden_Base = &b.Base
	x.xxx_hidden_Compared = &b.Compared
	return m0
}

type SyncOutput struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_StartedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3"`
	xxx_hidden_EndedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ended_at,json=endedAt,proto3"`
	xxx_hidden_SyncToken    string                 `protobuf:"bytes,4,opt,name=sync_token,json=syncToken,proto3"`
	xxx_hidden_SyncType     string                 `protobuf:"bytes,5,opt,name=sync_type,json=syncType,proto3"`
	xxx_hidden_ParentSyncId string                 `protobuf:"bytes,6,opt,name=parent_sync_id,json=parentSyncId,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SyncOutput) Reset() {
	*x = SyncOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOutput) ProtoMessage() {}

func (x *SyncOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncOutput) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *SyncOutput) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartedAt
	}
	return nil
}

func (x *SyncOutput) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EndedAt
	}
	return nil
}

func (x *SyncOutput) GetSyncToken() string {
	if x != nil {
		return x.xxx_hidden_SyncToken
	}
	return ""
}

func (x *SyncOutput) GetSyncType() string {
	if x != nil {
		return x.xxx_hidden_SyncType
	}
	return ""
}

func (x *SyncOutput) GetParentSyncId() string {
	if x != nil {
		return x.xxx_hidden_ParentSyncId
	}
	return ""
}

func (x *SyncOutput) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *SyncOutput) SetStartedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartedAt = v
}

func (x *SyncOutput) SetEndedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_EndedAt = v
}

func (x *SyncOutput) SetSyncToken(v string) {
	x.xxx_hidden_SyncToken = v
}

func (x *SyncOutput) SetSyncType(v string) {
	x.xxx_hidden_SyncType = v
}

func (x *SyncOutput) SetParentSyncId(v string) {
	x.xxx_hidden_ParentSyncId = v
}

func (x *SyncOutput) HasStartedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartedAt != nil
}

func (x *SyncOutput) HasEndedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EndedAt != nil
}

func (x *SyncOutput) ClearStartedAt() {
	x.xxx_hidden_StartedAt = nil
}

func (x *SyncOutput) ClearEndedAt() {
	x.xxx_hidden_EndedAt = nil
}

type SyncOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id           string
	StartedAt    *timestamppb.Timestamp
	EndedAt      *timestamppb.Timestamp
	SyncToken    string
	SyncType     string
	ParentSyncId string
}

func (b0 SyncOutput_builder) Build() *SyncOutput {
	m0 := &SyncOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_StartedAt = b.StartedAt
	x.xxx_hidden_EndedAt = b.EndedAt
	x.xxx_hidden_SyncToken = b.SyncToken
	x.xxx_hidden_SyncType = b.SyncType
	x.xxx_hidden_ParentSyncId = b.ParentSyncId
	return m0
}

type SyncListOutput struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Syncs *[]*SyncOutput         `protobuf:"bytes,1,rep,name=syncs,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncListOutput) Reset() {
	*x = SyncListOutput{}
	mi := &file_baton_v1_outputs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncListOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncListOutput) ProtoMessage() {}

func (x *SyncListOutput) ProtoReflect() protoreflect.Message {
	mi := &file_baton_v1_outputs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncListOutput) GetSyncs() []*SyncOutput {
	if x != nil {
		if x.xxx_hidden_Syncs != nil {
			return *x.xxx_hidden_Syncs
		}
	}
	return nil
}

func (x *SyncListOutput) SetSyncs(v []*SyncOutput) {
	x.xxx_hidden_Syncs = &v
}

type SyncListOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Syncs []*SyncOutput
}

func (b0 SyncListOutput_builder) Build() *SyncListOutput {
	m0 := &SyncListOutput{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Syncs = &b.Syncs
	return m0
}

var File_baton_v1_outputs_proto protoreflect.FileDescriptor

const file_baton_v1_outputs_proto_rawDesc = "" +
	"\n" +
	"\x16baton/v1/outputs.proto\x12\bbaton.v1\x1a!c1/connector/v2/entitlement.proto\x1a\x1bc1/connector/v2/grant.proto\x1a\x1ec1/connector/v2/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x01\n" +
	"\fResourceDiff\x123\n" +
	"\acreated\x18\x01 \x03(\v2\x19.c1.connector.v2.ResourceR\acreated\x123\n" +
	"\adeleted\x18\x02 \x03(\v2\x19.c1.connector.v2.ResourceR\adeleted\x125\n" +
	"\bmodified\x18\x03 \x03(\v2\x19.c1.connector.v2.ResourceR\bmodified\"\xbb\x01\n" +
	"\x0fEntitlementDiff\x126\n" +
	"\acreated\x18\x01 \x03(\v2\x1c.c1.connector.v2.EntitlementR\acreated\x126\n" +
	"\adeleted\x18\x02 \x03(\v2\x1c.c1.connector.v2.EntitlementR\adeleted\x128\n" +
	"\bmodified\x18\x03 \x03(\v2\x1c.c1.connector.v2.EntitlementR\bmodified\"\xa3\x01\n" +
	"\tGrantDiff\x120\n" +
	"\acreated\x18\x01 \x03(\v2\x16.c1.connector.v2.GrantR\acreated\x120\n" +
	"\adeleted\x18\x02 \x03(\v2\x16.c1.connector.v2.GrantR\adeleted\x122\n" +
	"\bmodified\x18\x03 \x03(\v2\x16.c1.connector.v2.GrantR\bmodified\"\xb1\x01\n" +
	"\rC1ZDiffOutput\x124\n" +
	"\tresources\x18\x01 \x01(\v2\x16.baton.v1.ResourceDiffR\tresources\x12=\n" +
	"\fentitlements\x18\x02 \x01(\v2\x19.baton.v1.EntitlementDiffR\fentitlements\x12+\n" +
	"\x06grants\x18\x03 \x01(\v2\x13.baton.v1.GrantDiffR\x06grants\"X\n" +
	"\x12ResourceTypeOutput\x12B\n" +
	"\rresource_type\x18\x01 \x01(\v2\x1d.c1.connector.v2.ResourceTypeR\fresourceType\"\xbe\x01\n" +
	"\x0eResourceOutput\x125\n" +
	"\bresource\x18\x01 \x01(\v2\x19.c1.connector.v2.ResourceR\bresource\x12B\n" +
	"\rresource_type\x18\x02 \x01(\v2\x1d.c1.connector.v2.ResourceTypeR\fresourceType\x121\n" +
	"\x06parent\x18\x03 \x01(\v2\x19.c1.connector.v2.ResourceR\x06parent\"\xce\x01\n" +
	"\x11EntitlementOutput\x12>\n" +
	"\ventitlement\x18\x01 \x01(\v2\x1c.c1.connector.v2.EntitlementR\ventitlement\x125\n" +
	"\bresource\x18\x02 \x01(\v2\x19.c1.connector.v2.ResourceR\bresource\x12B\n" +
	"\rresource_type\x18\x03 \x01(\v2\x1d.c1.connector.v2.ResourceTypeR\fresourceType\"\xaf\x02\n" +
	"\vGrantOutput\x12,\n" +
	"\x05grant\x18\x01 \x01(\v2\x16.c1.connector.v2.GrantR\x05grant\x12>\n" +
	"\ventitlement\x18\x02 \x01(\v2\x1c.c1.connector.v2.EntitlementR\ventitlement\x125\n" +
	"\bresource\x18\x03 \x01(\v2\x19.c1.connector.v2.ResourceR\bresource\x12B\n" +
	"\rresource_type\x18\x04 \x01(\v2\x1d.c1.connector.v2.ResourceTypeR\fresourceType\x127\n" +
	"\tprincipal\x18\x05 \x01(\v2\x19.c1.connector.v2.ResourceR\tprincipal\"\xd3\x01\n" +
	"\x14ResourceAccessOutput\x12B\n" +
	"\rresource_type\x18\x01 \x01(\v2\x1d.c1.connector.v2.ResourceTypeR\fresourceType\x125\n" +
	"\bresource\x18\x02 \x01(\v2\x19.c1.connector.v2.ResourceR\bresource\x12@\n" +
	"\fentitlements\x18\x03 \x03(\v2\x1c.c1.connector.v2.EntitlementR\fentitlements\"]\n" +
	"\x16ResourceTypeListOutput\x12C\n" +
	"\x0eresource_types\x18\x01 \x03(\v2\x1c.baton.v1.ResourceTypeOutputR\rresourceTypes\"L\n" +
	"\x12ResourceListOutput\x126\n" +
	"\tresources\x18\x01 \x03(\v2\x18.baton.v1.ResourceOutputR\tresources\"X\n" +
	"\x15EntitlementListOutput\x12?\n" +
	"\fentitlements\x18\x01 \x03(\v2\x1b.baton.v1.EntitlementOutputR\fentitlements\"@\n" +
	"\x0fGrantListOutput\x12-\n" +
	"\x06grants\x18\x01 \x03(\v2\x15.baton.v1.GrantOutputR\x06grants\"\x8b\x01\n" +
	"\x18ResourceAccessListOutput\x127\n" +
	"\tprincipal\x18\x01 \x01(\v2\x19.c1.connector.v2.ResourceR\tprincipal\x126\n" +
	"\x06access\x18\x02 \x03(\v2\x1e.baton.v1.ResourceAccessOutputR\x06access\"\xe1\x01\n" +
	"\x17PrincipalsCompareOutput\x122\n" +
	"\amissing\x18\x01 \x03(\v2\x18.baton.v1.ResourceOutputR\amissing\x12.\n" +
	"\x05extra\x18\x02 \x03(\v2\x18.baton.v1.ResourceOutputR\x05extra\x12,\n" +
	"\x04base\x18\x03 \x03(\v2\x18.baton.v1.ResourceOutputR\x04base\x124\n" +
	"\bcompared\x18\x04 \x03(\v2\x18.baton.v1.ResourceOutputR\bcompared\"\xf0\x01\n" +
	"\n" +
	"SyncOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x1d\n" +
	"\n" +
	"sync_token\x18\x04 \x01(\tR\tsyncToken\x12\x1b\n" +
	"\tsync_type\x18\x05 \x01(\tR\bsyncType\x12$\n" +
	"\x0eparent_sync_id\x18\x06 \x01(\tR\fparentSyncId\"<\n" +
	"\x0eSyncListOutput\x12*\n" +
	"\x05syncs\x18\x01 \x03(\v2\x14.baton.v1.SyncOutputR\x05syncsB3Z1github.com/conductorone/baton-sdk/pb/baton_cli/v1b\x06proto3"

var file_baton_v1_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_baton_v1_outputs_proto_goTypes = []any{
	(*ResourceDiff)(nil),             // 0: baton.v1.ResourceDiff
	(*EntitlementDiff)(nil),          // 1: baton.v1.EntitlementDiff
	(*GrantDiff)(nil),                // 2: baton.v1.GrantDiff
	(*C1ZDiffOutput)(nil),            // 3: baton.v1.C1ZDiffOutput
	(*ResourceTypeOutput)(nil),       // 4: baton.v1.ResourceTypeOutput
	(*ResourceOutput)(nil),           // 5: baton.v1.ResourceOutput
	(*EntitlementOutput)(nil),        // 6: baton.v1.EntitlementOutput
	(*GrantOutput)(nil),              // 7: baton.v1.GrantOutput
	(*ResourceAccessOutput)(nil),     // 8: baton.v1.ResourceAccessOutput
	(*ResourceTypeListOutput)(nil),   // 9: baton.v1.ResourceTypeListOutput
	(*ResourceListOutput)(nil),       // 10: baton.v1.ResourceListOutput
	(*EntitlementListOutput)(nil),    // 11: baton.v1.EntitlementListOutput
	(*GrantListOutput)(nil),          // 12: baton.v1.GrantListOutput
	(*ResourceAccessListOutput)(nil), // 13: baton.v1.ResourceAccessListOutput
	(*PrincipalsCompareOutput)(nil),  // 14: baton.v1.PrincipalsCompareOutput
	(*SyncOutput)(nil),               // 15: baton.v1.SyncOutput
	(*SyncListOutput)(nil),           // 16: baton.v1.SyncListOutput
	(*v2.Resource)(nil),              // 17: c1.connector.v2.Resource
	(*v2.Entitlement)(nil),           // 18: c1.connector.v2.Entitlement
	(*v2.Grant)(nil),                 // 19: c1.connector.v2.Grant
	(*v2.ResourceType)(nil),          // 20: c1.connector.v2.ResourceType
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
}
var file_baton_v1_outputs_proto_depIdxs = []int32{
	17, // 0: baton.v1.ResourceDiff.created:type_name -> c1.connector.v2.Resource
	17, // 1: baton.v1.ResourceDiff.deleted:type_name -> c1.connector.v2.Resource
	17, // 2: baton.v1.ResourceDiff.modified:type_name -> c1.connector.v2.Resource
	18, // 3: baton.v1.EntitlementDiff.created:type_name -> c1.connector.v2.Entitlement
	18, // 4: baton.v1.EntitlementDiff.deleted:type_name -> c1.connector.v2.Entitlement
	18, // 5: baton.v1.EntitlementDiff.modified:type_name -> c1.connector.v2.Entitlement
	19, // 6: baton.v1.GrantDiff.created:type_name -> c1.connector.v2.Grant
	19, // 7: baton.v1.GrantDiff.deleted:type_name -> c1.connector.v2.Grant
	19, // 8: baton.v1.GrantDiff.modified:type_name -> c1.connector.v2.Grant
	0,  // 9: baton.v1.C1ZDiffOutput.resources:type_name -> baton.v1.ResourceDiff
	1,  // 10: baton.v1.C1ZDiffOutput.entitlements:type_name -> baton.v1.EntitlementDiff
	2,  // 11: baton.v1.C1ZDiffOutput.grants:type_name -> baton.v1.GrantDiff
	20, // 12: baton.v1.ResourceTypeOutput.resource_type:type_name -> c1.connector.v2.ResourceType
	17, // 13: baton.v1.ResourceOutput.resource:type_name -> c1.connector.v2.Resource
	20, // 14: baton.v1.ResourceOutput.resource_type:type_name -> c1.connector.v2.ResourceType
	17, // 15: baton.v1.ResourceOutput.parent:type_name -> c1.connector.v2.Resource
	18, // 16: baton.v1.EntitlementOutput.entitlement:type_name -> c1.connector.v2.Entitlement
	17, // 17: baton.v1.EntitlementOutput.resource:type_name -> c1.connector.v2.Resource
	20, // 18: baton.v1.EntitlementOutput.resource_type:type_name -> c1.connector.v2.ResourceType
	19, // 19: baton.v1.GrantOutput.grant:type_name -> c1.connector.v2.Grant
	18, // 20: baton.v1.GrantOutput.entitlement:type_name -> c1.connector.v2.Entitlement
	17, // 21: baton.v1.GrantOutput.resource:type_name -> c1.connector.v2.Resource
	20, // 22: baton.v1.GrantOutput.resource_type:type_name -> c1.connector.v2.ResourceType
	17, // 23: baton.v1.GrantOutput.principal:type_name -> c1.connector.v2.Resource
	20, // 24: baton.v1.ResourceAccessOutput.resource_type:type_name -> c1.connector.v2.ResourceType
	17, // 25: baton.v1.ResourceAccessOutput.resource:type_name -> c1.connector.v2.Resource
	18, // 26: baton.v1.ResourceAccessOutput.entitlements:type_name -> c1.connector.v2.Entitlement
	4,  // 27: baton.v1.ResourceTypeListOutput.resource_types:type_name -> baton.v1.ResourceTypeOutput
	5,  // 28: baton.v1.ResourceListOutput.resources:type_name -> baton.v1.ResourceOutput
	6,  // 29: baton.v1.EntitlementListOutput.entitlements:type_name -> baton.v1.EntitlementOutput
	7,  // 30: baton.v1.GrantListOutput.grants:type_name -> baton.v1.GrantOutput
	17, // 31: baton.v1.ResourceAccessListOutput.principal:type_name -> c1.connector.v2.Resource
	8,  // 32: baton.v1.ResourceAccessListOutput.access:type_name -> baton.v1.ResourceAccessOutput
	5,  // 33: baton.v1.PrincipalsCompareOutput.missing:type_name -> baton.v1.ResourceOutput
	5,  // 34: baton.v1.PrincipalsCompareOutput.extra:type_name -> baton.v1.ResourceOutput
	5,  // 35: baton.v1.PrincipalsCompareOutput.base:type_name -> baton.v1.ResourceOutput
	5,  // 36: baton.v1.PrincipalsCompareOutput.compared:type_name -> baton.v1.ResourceOutput
	21, // 37: baton.v1.SyncOutput.started_at:type_name -> google.protobuf.Timestamp
	21, // 38: baton.v1.SyncOutput.ended_at:type_name -> google.protobuf.Timestamp
	15, // 39: baton.v1.SyncListOutput.syncs:type_name -> baton.v1.SyncOutput
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_baton_v1_outputs_proto_init() }
func file_baton_v1_outputs_proto_init() {
	if File_baton_v1_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baton_v1_outputs_proto_rawDesc), len(file_baton_v1_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_baton_v1_outputs_proto_goTypes,
		DependencyIndexes: file_baton_v1_outputs_proto_depIdxs,
		MessageInfos:      file_baton_v1_outputs_proto_msgTypes,
	}.Build()
	File_baton_v1_outputs_proto = out.File
	file_baton_v1_outputs_proto_goTypes = nil
	file_baton_v1_outputs_proto_depIdxs = nil
}
