name: ci
on: pull_request
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.2
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        go-version: [1.25.2]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: go tests
        run: go test -v -covermode=count -json ./... > test.json
      - name: Print go test results
        if: always()
        run: cat test.json
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.8.0
        with:
          test-results: test.json
  buf-lint-and-breaking-change-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: bufbuild/buf-setup-action@v1
        with:
          version: '1.50.0'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        uses: bufbuild/buf-lint-action@v1
      - name: Breaking change detection against `main`
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/conductorone/baton-sdk.git#branch=main'
  baton-demo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: baton-sdk
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: baton-sdk/go.mod
      - name: Checkout baton-demo
        uses: actions/checkout@v4
        with:
          repository: conductorone/baton-demo
          path: baton-demo
          ref: main
      - name: Replace baton-sdk with local version
        run: |
          cd baton-demo
          go mod edit -replace github.com/conductorone/baton-sdk=../baton-sdk
          go mod tidy && go mod vendor
      - name: Build baton-demo
        run: |
          cd baton-demo
          go build ./cmd/baton-demo
      - name: Initialize database
        run: ./baton-demo/baton-demo --init-db
      - name: Test grant/revoke
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-demo/baton-demo
          baton-entitlement: 'group:group-0000001:member'
          baton-principal: 'user-0000000'
          baton-principal-type: 'user'
      - name: Test create account
        uses: ConductorOne/github-workflows/actions/account-provisioning@v3
        with:
          connector: ./baton-demo/baton-demo
          account-email: testuser1@example.com
          account-login: testuser1
          account-profile: '{"username": "testuser1", "email": "testuser1@example.com", "firstName": "test", "lastName": "user1"}'
      - name: Test rotate credentials
        run: ./baton-demo/baton-demo --rotate-credentials=user-0000000 --rotate-credentials-type=user
