name: main ci
on:
  push:
    branches:
      - main
jobs:
  lint-and-breaking-change-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: bufbuild/buf-setup-action@v1
        with:
          version: '1.50.0'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        uses: bufbuild/buf-lint-action@v1
      - name: Breaking change detection against `main`
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/conductorone/baton-sdk.git#branch=main,ref=HEAD~1'
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.2
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        go-version: [ 1.25.2 ]
        platform: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: go tests
        run: go test -tags=baton_lambda_support -v -covermode=count -json ./... > test.json
      - name: Print go test results
        if: always()
        run: cat test.json
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.8.0
        with:
          test-results: test.json
