name: Update hard-coded SDK version
on:
  release:
    types: [published, unpublished, created, edited, deleted, released]

jobs:
  update-sdk-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELENG_GITHUB_TOKEN }}
          fetch-depth: 0
          fetch-tags: true

      - name: Update hard-coded SDK version
        run: make pkg/sdk/version.go

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: main
          default_author: github_actions
          message: "Update SDK version to ${{ github.ref_name }}"
          add: "pkg/sdk/version.go"
